-- =====================================================================
-- 도시 사진 — 위키백과 대표 이미지 131 곳
--
-- 015 다음에 실행합니다.
--
-- **상용으로 갈 때는 정리해야 합니다.** 위키미디어 이미지는 대부분 CC-BY-SA 라
-- 출처 표기가 필요하고, 남의 서버에서 직접 끌어다 쓰는 것(핫링크)은 권장되지
-- 않습니다. 우리 Storage 로 옮기거나 다른 출처로 바꾸는 것이 맞습니다.
-- 지금은 화면을 만들어 보는 것이 목적이라 이대로 씁니다.
--
-- 못 찾은 곳은 사진 없이 둡니다. 화면에서 첫 글자로 대신 그립니다.
-- =====================================================================

update public.cities c set image_url = v.url
from (values
  ('abudhabi','https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Abu_dhabi_skylines_2014.jpg/640px-Abu_dhabi_skylines_2014.jpg'),
  ('amsterdam','https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Canals_of_Amsterdam_-_Jordaan_area.jpg/640px-Canals_of_Amsterdam_-_Jordaan_area.jpg'),
  ('athens','https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Athens_Acropolis_at_Daybreak.jpg/640px-Athens_Acropolis_at_Daybreak.jpg'),
  ('auckland','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Auckland_skyline_-_May_2024_%282%29.jpg/640px-Auckland_skyline_-_May_2024_%282%29.jpg'),
  ('bali','https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Bali_in_Indonesia_%28special_marker%29.svg/640px-Bali_in_Indonesia_%28special_marker%29.svg.png'),
  ('bangkok','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Bangkok_montage_3.jpg/640px-Bangkok_montage_3.jpg'),
  ('barcelona','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Evening_light_over_Barcelona.jpg/640px-Evening_light_over_Barcelona.jpg'),
  ('basel','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Basel_-_M%C3%BCnsterpfalz1.jpg/640px-Basel_-_M%C3%BCnsterpfalz1.jpg'),
  ('beijing','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Skyline_of_Beijing_CBD_with_B-5906_approaching_%2820211016171955%29_%281%29.jpg/640px-Skyline_of_Beijing_CBD_with_B-5906_approaching_%2820211016171955%29_%281%29.jpg'),
  ('beppu','https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Beppu_Montage_2.jpg/640px-Beppu_Montage_2.jpg'),
  ('berlin','https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Berlin_Panorama_von_der_Siegess%C3%A4ule_2021.jpg/640px-Berlin_Panorama_von_der_Siegess%C3%A4ule_2021.jpg'),
  ('boracay','https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Boracay_White_Beach_in_day_%28985286231%29.jpg/640px-Boracay_White_Beach_in_day_%28985286231%29.jpg'),
  ('boston','https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Massachusetts_State_House_-_panoramio_%281%29.jpg/640px-Massachusetts_State_House_-_panoramio_%281%29.jpg'),
  ('brisbane','https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Brisbane_CBD_seen_from_Kangaroo_Point%2C_2024%2C_01_%282%29.jpg/640px-Brisbane_CBD_seen_from_Kangaroo_Point%2C_2024%2C_01_%282%29.jpg'),
  ('brussels','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/TE-Collage_Brussels.png/640px-TE-Collage_Brussels.png'),
  ('budapest','https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/The_building_of_the_Hungarian_Parliament_%2810890208584%29.jpg/640px-The_building_of_the_Hungarian_Parliament_%2810890208584%29.jpg'),
  ('busan','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Busan_City_Haeundae_District_%2801%29.jpg/640px-Busan_City_Haeundae_District_%2801%29.jpg'),
  ('cairo','https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Cairo_Montage.png/640px-Cairo_Montage.png'),
  ('cancun','https://upload.wikimedia.org/wikipedia/ko/thumb/d/d5/Cancun_from_hotel_room%28Riu_Cancun%29.jpg/640px-Cancun_from_hotel_room%28Riu_Cancun%29.jpg'),
  ('capetown','https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Cape_Town_Montage_2015.png/640px-Cape_Town_Montage_2015.png'),
  ('cappadocia','https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Cappadocia_balloon_trip%2C_Ortahisar_Castle_%2811893715185%29.jpg/640px-Cappadocia_balloon_trip%2C_Ortahisar_Castle_%2811893715185%29.jpg'),
  ('cebu','https://upload.wikimedia.org/wikipedia/commons/e/e8/Ph_locator_cebu_cebu.png'),
  ('chengdu','https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/%E9%9B%AA%E5%B1%B1%E4%B8%8B%E7%9A%84%E6%88%90%E9%83%BD%E5%B8%82%E5%A4%A9%E9%99%85%E7%BA%BF_Chengdu_skyline_with_snow_capped_mountains.jpg/640px-%E9%9B%AA%E5%B1%B1%E4%B8%8B%E7%9A%84%E6%88%90%E9%83%BD%E5%B8%82%E5%A4%A9%E9%99%85%E7%BA%BF_Chengdu_skyline_with_snow_capped_mountains.jpg'),
  ('chiangmai','https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Chiang_Mai_City.png/640px-Chiang_Mai_City.png'),
  ('copenhagen','https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Copenhagen_Collage.jpg/640px-Copenhagen_Collage.jpg'),
  ('cusco','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Cusco%2C_Peru.png/640px-Cusco%2C_Peru.png'),
  ('daegu','https://upload.wikimedia.org/wikipedia/commons/5/52/Daegu_montage.png'),
  ('danang','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Han_River_Bridge_in_Vietnam_Night_View.jpg/640px-Han_River_Bridge_in_Vietnam_Night_View.jpg'),
  ('delhi','https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Jama_Masjid_2011.jpg/640px-Jama_Masjid_2011.jpg'),
  ('doha','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Doha_montage.jpg/640px-Doha_montage.jpg'),
  ('dubai','https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/DubaiCollage.jpg/640px-DubaiCollage.jpg'),
  ('dublin','https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/IRL_Dublin_flag.svg/langko-330px-IRL_Dublin_flag.svg.png'),
  ('dubrovnik','https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/The_walls_of_the_fortress_and_View_of_the_old_city._panorama.jpg/640px-The_walls_of_the_fortress_and_View_of_the_old_city._panorama.jpg'),
  ('edinburgh','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Skyline_of_Edinburgh.jpg/640px-Skyline_of_Edinburgh.jpg'),
  ('florence','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/FirenzeDec092023_01.jpg/640px-FirenzeDec092023_01.jpg'),
  ('frankfurt','https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Frankfurt_collage.jpg/640px-Frankfurt_collage.jpg'),
  ('fukuoka','https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Fukuoka_Skyline_of_Seaside_Momochi.jpg/640px-Fukuoka_Skyline_of_Seaside_Momochi.jpg'),
  ('gangneung','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Gangneung_City_Hall_2.jpg/640px-Gangneung_City_Hall_2.jpg'),
  ('guam','https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/langko-330px-Flag_of_Guam.svg.png'),
  ('guangzhou','https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Guangzhou_montage.jpg/640px-Guangzhou_montage.jpg'),
  ('hakodate','https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Hakodate_montage.jpg/640px-Hakodate_montage.jpg'),
  ('hanoi','https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Hanoi_Panorama_-_NKS.jpg/640px-Hanoi_Panorama_-_NKS.jpg'),
  ('helsinki','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Helsinki_uusimaa.png/640px-Helsinki_uusimaa.png'),
  ('hiroshima','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Atomic_Bomb_Dome_and_Motoyaso_River%2C_Hiroshima%2C_Northwest_view_20190417_1.jpg/640px-Atomic_Bomb_Dome_and_Motoyaso_River%2C_Hiroshima%2C_Northwest_view_20190417_1.jpg'),
  ('hochiminh','https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Ho_Chi_Minh_-_1946_Portrait.jpg/640px-Ho_Chi_Minh_-_1946_Portrait.jpg'),
  ('hoian','https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ch%E1%BB%A3_H%E1%BB%99i_An_-_Hoi_An_Market_%282024%29_-_img_02.jpg/640px-Ch%E1%BB%A3_H%E1%BB%99i_An_-_Hoi_An_Market_%282024%29_-_img_02.jpg'),
  ('hongkong','https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/langko-330px-Flag_of_Hong_Kong.svg.png'),
  ('honolulu','https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Downtown_Honolulu_from_P%C5%ABowaina_%28Punchbowl_Crater%29.jpg/640px-Downtown_Honolulu_from_P%C5%ABowaina_%28Punchbowl_Crater%29.jpg'),
  ('incheon','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Songdo_Central_Park_and_Posco_Tower_Songdo.jpg/640px-Songdo_Central_Park_and_Posco_Tower_Songdo.jpg'),
  ('interlaken','https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Goldswil-Viadukt_Panorama_mit_Interlaken_im_Hintergrund_2.jpg/640px-Goldswil-Viadukt_Panorama_mit_Interlaken_im_Hintergrund_2.jpg'),
  ('istanbul','https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Historical_peninsula_and_modern_skyline_of_Istanbul.jpg/640px-Historical_peninsula_and_modern_skyline_of_Istanbul.jpg'),
  ('jakarta','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Jakarta_Skyline_Part_2.jpg/640px-Jakarta_Skyline_Part_2.jpg'),
  ('jeonju','https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Jeonju_City_Hall_20230408_004.jpg/640px-Jeonju_City_Hall_20230408_004.jpg'),
  ('kanazawa','https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Kanazawa_montage.jpg/640px-Kanazawa_montage.jpg'),
  ('kaohsiung','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Cityscape_of_Kaohsiung%2C_Taiwan_202303.jpg/640px-Cityscape_of_Kaohsiung%2C_Taiwan_202303.jpg'),
  ('kobe','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Port_of_Kobe02s4100.jpg/640px-Port_of_Kobe02s4100.jpg'),
  ('kotakinabalu','https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Panoramic_view_of_Kota_Kinabalu_City.jpg/640px-Panoramic_view_of_Kota_Kinabalu_City.jpg'),
  ('krabi','https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Wat_Tham_Sua_18.jpg/640px-Wat_Tham_Sua_18.jpg'),
  ('krakow','https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Zamek_Kr%C3%B3lewski_na_Wawelu_%281%29.jpg/640px-Zamek_Kr%C3%B3lewski_na_Wawelu_%281%29.jpg'),
  ('kualalumpur','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Bukit_Bintang_Junction_in_2023.jpg/640px-Bukit_Bintang_Junction_in_2023.jpg'),
  ('kumamoto','https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Mount_Tatsuda-yama_%28Kumamoto%29_1.jpg/640px-Mount_Tatsuda-yama_%28Kumamoto%29_1.jpg'),
  ('kyoto','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Location_KyotoJapan.jpg/640px-Location_KyotoJapan.jpg'),
  ('lasvegas','https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Las_Vegas_Skyline_at_night_North_%287314937576%29.jpg/640px-Las_Vegas_Skyline_at_night_North_%287314937576%29.jpg'),
  ('lima','https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Bas%C3%ADlica_Catedral_Metropolitana_de_Lima_%28cropped%29.jpg/640px-Bas%C3%ADlica_Catedral_Metropolitana_de_Lima_%28cropped%29.jpg'),
  ('lisbon','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Lisboa_-_Portugal_%2852597836992%29.jpg/640px-Lisboa_-_Portugal_%2852597836992%29.jpg'),
  ('london','https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/London_Montage_A.jpg/640px-London_Montage_A.jpg'),
  ('losangeles','https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/LA_County_Incorporated_Areas_Los_Angeles_highlighted.svg/langko-330px-LA_County_Incorporated_Areas_Los_Angeles_highlighted.svg.png'),
  ('macau','https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/langko-330px-Flag_of_Macau.svg.png'),
  ('madrid','https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Plaza_Mayor_De_Madrid_%28215862629%29_edited.jpeg/640px-Plaza_Mayor_De_Madrid_%28215862629%29_edited.jpeg'),
  ('manila','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cityscape_of_Manila%2C_2025_%2801%29.jpg/640px-Cityscape_of_Manila%2C_2025_%2801%29.jpg'),
  ('marrakech','https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Koutoubia_Mosque%2CMarrakech%2CMorocco.jpg/640px-Koutoubia_Mosque%2CMarrakech%2CMorocco.jpg'),
  ('melbourne','https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Melbourne_skyline_sor.jpg/640px-Melbourne_skyline_sor.jpg'),
  ('mexicocity','https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Montaje_de_CDMX.jpg/640px-Montaje_de_CDMX.jpg'),
  ('miami','https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Miami_collage_20110330.jpg/640px-Miami_collage_20110330.jpg'),
  ('milan','https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Milan.Proper.Wikipedia.Image.png/640px-Milan.Proper.Wikipedia.Image.png'),
  ('montreal','https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Montreal%2C_Quebec_skyline.jpg/640px-Montreal%2C_Quebec_skyline.jpg'),
  ('mumbai','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Mumbai_Bandra-Worli_Sea_Link.jpg/640px-Mumbai_Bandra-Worli_Sea_Link.jpg'),
  ('munich','https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Munchen_collage.jpg/640px-Munchen_collage.jpg'),
  ('nagasaki','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Nagasaki_City_View_from_Glover_Garden%2C_Nagasaki_2014.jpg/640px-Nagasaki_City_View_from_Glover_Garden%2C_Nagasaki_2014.jpg'),
  ('nagoya','https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Nagoya_Station_at_night01.jpg/640px-Nagoya_Station_at_night01.jpg'),
  ('nairobi','https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Nairobi_Montage_A.jpg/640px-Nairobi_Montage_A.jpg'),
  ('naples','https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Napoli_-_Maschio_Angioino_-_202209302342_3.jpg/640px-Napoli_-_Maschio_Angioino_-_202209302342_3.jpg'),
  ('nara','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/World_Map_%28political%29.svg/langko-330px-World_Map_%28political%29.svg.png'),
  ('newyork','https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/NYC_Montage_2011.jpg/640px-NYC_Montage_2011.jpg'),
  ('nhatrang','https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Nha_Trang_banner.jpg/640px-Nha_Trang_banner.jpg'),
  ('nice','https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Promenade_des_Anglais_Nice_IMG_1255.jpg/640px-Promenade_des_Anglais_Nice_IMG_1255.jpg'),
  ('okinawa','https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Naha_Shuri_Castle16s5s3200.jpg/640px-Naha_Shuri_Castle16s5s3200.jpg'),
  ('orlando','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/The_city_beautiful.jpg/640px-The_city_beautiful.jpg'),
  ('osaka','https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Osaka_Castle_03bs3200.jpg/640px-Osaka_Castle_03bs3200.jpg'),
  ('oslo','https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Oslo_newer_montage_2013.png/640px-Oslo_newer_montage_2013.png'),
  ('paris','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/640px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg'),
  ('pattaya','https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Montage_Pattaya.jpg/640px-Montage_Pattaya.jpg'),
  ('penang','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Penang_%28Malaysia%29.svg/langko-330px-Flag_of_Penang_%28Malaysia%29.svg.png'),
  ('phnompenh','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Phnom_Penh_aerial.jpg/640px-Phnom_Penh_aerial.jpg'),
  ('phuket','https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Phuket_Aerial.jpg/640px-Phuket_Aerial.jpg'),
  ('phuquoc','https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Bai-sao-phu-quoc-tuonglamphotos.jpg/640px-Bai-sao-phu-quoc-tuonglamphotos.jpg'),
  ('porto','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Porto_montage.PNG/640px-Porto_montage.PNG'),
  ('prague','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Prague_collage_2018.jpg/640px-Prague_collage_2018.jpg'),
  ('qingdao','https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Qingdao_Harbour_51341-Qingdao_%2849055637186%29.jpg/640px-Qingdao_Harbour_51341-Qingdao_%2849055637186%29.jpg'),
  ('reykjavik','https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Reykjavik_Main_Image.jpg/640px-Reykjavik_Main_Image.jpg'),
  ('rio','https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Rio_Collage.png/640px-Rio_Collage.png'),
  ('rome','https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/RomaMontage1..jpg/640px-RomaMontage1..jpg'),
  ('saipan','https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Saipan_USGS_1999_map.jpg/640px-Saipan_USGS_1999_map.jpg'),
  ('salzburg','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/SalzburgerAltstadt02.JPG/640px-SalzburgerAltstadt02.JPG'),
  ('sanfrancisco','https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/SF_From_Marin_Highlands3.jpg/640px-SF_From_Marin_Highlands3.jpg'),
  ('santiago','https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Palacio_de_La_Moneda_-_miguelreflex.jpg/640px-Palacio_de_La_Moneda_-_miguelreflex.jpg'),
  ('santorini','https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/2011_Dimos_Thiras.png/640px-2011_Dimos_Thiras.png'),
  ('saopaulo','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Novo_MASP.jpg/640px-Novo_MASP.jpg'),
  ('sapporo','https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/JR_Tower_Square.jpg/640px-JR_Tower_Square.jpg'),
  ('seattle','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Space_Needle002.jpg/640px-Space_Needle002.jpg'),
  ('sendai','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/SendaiCity_Skylines_from_Mukaiyama2018.jpg/640px-SendaiCity_Skylines_from_Mukaiyama2018.jpg'),
  ('seoul','https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/%EC%A4%91%ED%99%94%EC%A0%84%EC%9D%98_%EB%82%AE.jpg/640px-%EC%A4%91%ED%99%94%EC%A0%84%EC%9D%98_%EB%82%AE.jpg'),
  ('seville','https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/9._Mai_1929%2C_an_diesem_Tag_wurde_die_Iberoamerikanische_Ausstellung_in_Sevilla_er%C3%B6ffnet._09.jpg/640px-9._Mai_1929%2C_an_diesem_Tag_wurde_die_Iberoamerikanische_Ausstellung_in_Sevilla_er%C3%B6ffnet._09.jpg'),
  ('shanghai','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Huangpu_Park_20124-Shanghai_%2832208802494%29.jpg/640px-Huangpu_Park_20124-Shanghai_%2832208802494%29.jpg'),
  ('siemreap','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Front_porch_of_Wat_Damnak.jpg/640px-Front_porch_of_Wat_Damnak.jpg'),
  ('singapore','https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/langko-330px-Flag_of_Singapore.svg.png'),
  ('sokcho','https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Korea-Sokcho-Expo_Tower-01.jpg/640px-Korea-Sokcho-Expo_Tower-01.jpg'),
  ('stockholm','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Stockholm.jpg/640px-Stockholm.jpg'),
  ('taichung','https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Taichung_montage.PNG/640px-Taichung_montage.PNG'),
  ('taipei','https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Taipei_Skyline_2022.06.29.jpg/640px-Taipei_Skyline_2022.06.29.jpg'),
  ('telaviv','https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/TelAvivAvivMetroo.png/640px-TelAvivAvivMetroo.png'),
  ('tokyo','https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Tokyo_Montage_2015.jpg/640px-Tokyo_Montage_2015.jpg'),
  ('toronto','https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Toronto_Skyline_viewed_from_Algonquin_Island_%2816-9_crop%29.jpg/640px-Toronto_Skyline_viewed_from_Algonquin_Island_%2816-9_crop%29.jpg'),
  ('vancouver','https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Concord_Pacific_Master_Plan_Area.jpg/640px-Concord_Pacific_Master_Plan_Area.jpg'),
  ('vienna','https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Schoenbrunn_philharmoniker_2012.jpg/640px-Schoenbrunn_philharmoniker_2012.jpg'),
  ('vientiane','https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Vientiane_-_Patuxai_-_0003.jpg/640px-Vientiane_-_Patuxai_-_0003.jpg'),
  ('warsaw','https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Aleja_Niepdleglosci_Warsaw_2022_aerial_%28cropped%29.jpg/640px-Aleja_Niepdleglosci_Warsaw_2022_aerial_%28cropped%29.jpg'),
  ('xian','https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg/640px-City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg'),
  ('yangon','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/ShwedagonPagoda.jpg/640px-ShwedagonPagoda.jpg'),
  ('yeosu','https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Map_Yeosu-si.png/640px-Map_Yeosu-si.png'),
  ('yokohama','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Minato_Mirai_In_Blue.jpg/640px-Minato_Mirai_In_Blue.jpg')

) as v(id, url)
where c.id = v.id;

select count(*) filter (where image_url is not null) as 사진있음,
       count(*) filter (where image_url is null)     as 사진없음,
       count(*)                                      as 전체
  from public.cities;
