-- =====================================================================
-- 도시 설명 — 위키백과 요약 (298 곳)
--
-- 022 로 만든 칸을 채웁니다.
--
-- **출처를 반드시 적어야 합니다.** 위키백과 글은 CC BY-SA 입니다.
-- 사진(Pexels)과 달리 표기 의무가 있어서 원문 주소를 같이 저장했고
-- 화면에서 "위키백과" 링크로 답니다.
--
-- 못 찾은 곳은 비워 둡니다. 그런 도시는 나라 · 대륙 · 통화 · 시간대만 보여줍니다.
--
-- 023 다음에 실행합니다. 여러 번 실행해도 안전합니다.
-- =====================================================================

update public.cities c
   set summary = v.txt, summary_url = v.url
from (values
  ('abudhabi','아부다비는 아랍에미리트의 수도이다. 아라비아 반도의 아라비아 해안에 위치하고, 아랍에미리트를 구성하는 토후국 가운데 하나인 아부다비 토후국의 수도이다.','https://ko.wikipedia.org/wiki/%EC%95%84%EB%B6%80%EB%8B%A4%EB%B9%84'),
  ('adelaide','애들레이드는 오스트레일리아 사우스오스트레일리아주의 주도로, 남극해로 통하는 세인트빈센트 만에 있는 도시이다.','https://ko.wikipedia.org/wiki/%EC%95%A0%EB%93%A4%EB%A0%88%EC%9D%B4%EB%93%9C'),
  ('agra','아그라(Agra)는 인도 야무나 강변에 위치한 고대 도시로 우타르프라데시 주에 있다. 1526년부터 1658년까지 무굴 제국의 수도로 발달했는데, 당시 건설된 타지마할, 아그라 성 등은 세계문화유산으로 등록되어 있다.','https://ko.wikipedia.org/wiki/%EC%95%84%EA%B7%B8%EB%9D%BC'),
  ('almaty','알마티는 카자흐스탄의 최대 도시이다. 인구는 약 116만 8,000명이다.','https://ko.wikipedia.org/wiki/%EC%95%8C%EB%A7%88%ED%8B%B0'),
  ('amalfi','아말피는 이탈리아 캄파니아주 살레르노도의 마을이자 코무네(지방자치단체)로, 살레르노 만에 위치했다. 깊은 협곡이 바다와 만나는 지점, 몬테 체레토(Monte Cerreto, 해발 1,315m) 산기슭에 자리하고 있으며, 주변은 장엄한 절벽과 수려한 해안 풍경으로 둘러싸여 있다.','https://ko.wikipedia.org/wiki/%EC%95%84%EB%A7%90%ED%94%BC'),
  ('amman','암만은 요르단의 수도로, 암만주의 주도이다. 인구는 약 120만 명으로 요르단 전체 인구의 1/4을 차지하고 있으며 요르단의 정치, 경제의 중심지이기도 하다.','https://ko.wikipedia.org/wiki/%EC%95%94%EB%A7%8C'),
  ('amsterdam','암스테르담(Amsterdam,, UK also 듣기 )은 네덜란드의 수도이자 최대 도시이다. 그러나 행정의 중심지는 암스테르담으로부터 남서쪽으로 약 50 킬로미터 떨어진 헤이그에 있다.','https://ko.wikipedia.org/wiki/%EC%95%94%EC%8A%A4%ED%85%8C%EB%A5%B4%EB%8B%B4'),
  ('anchorage','앵커리지(Anchorage)는 미국 알래스카주 남부의 거의 중앙에 있는 항구 도시로, 주의 상공업과 금융, 문화, 관광의 중심지이며, 알래스카의 가장 큰 도시이자 인구의 40퍼센트 이상을 구성한다. 앵커리지는 1956년, 1965년, 1984/85년, 2002년 국가시민연맹에 의해, 4번 전미국대표시 상으로 지명된 상태이다.','https://ko.wikipedia.org/wiki/%EC%95%B5%EC%BB%A4%EB%A6%AC%EC%A7%80'),
  ('andong','안동시(安東市)는 대한민국 경상북도 중북부에 있는 도시이자, 경상북도청 소재지이다. 고려·조선시대에는 안동대도호부가 존재했다.','https://ko.wikipedia.org/wiki/%EC%95%88%EB%8F%99%EC%8B%9C'),
  ('aomori','Aomori , officially Aomori City, is the capital city of Aomori Prefecture, in the Tōhoku region of Japan. As of 1 August 2023, the city had an estimated population of 264,945 in 136,781 households, and a population dens…','https://en.wikipedia.org/wiki/Aomori'),
  ('athens','아테네는 그리스의 수도이자 최대의 도시이며, 아티키 주의 중심 도시이다. 세계적으로 오래된 도시이며, 역사 시대가 개막한 지 3,400년에 이른다.','https://ko.wikipedia.org/wiki/%EC%95%84%ED%85%8C%EB%84%A4'),
  ('auckland','Auckland is a large metropolitan city in the North Island of New Zealand. It has an urban population of about 1,547,200.','https://en.wikipedia.org/wiki/Auckland'),
  ('bagan','Bagan is an ancient city and a UNESCO World Heritage Site in the Mandalay Region of Myanmar. From the 9th to 13th centuries, the city was the capital of the Pagan Kingdom, the first kingdom that unified the regions that…','https://en.wikipedia.org/wiki/Bagan'),
  ('baku','바쿠는 아제르바이잔의 수도이다. 카스피해 서쪽에 뻗어 있는 압셰론 반도에 위치하고, 시가지는 반도 남쪽의 바쿠 만에 접한 항구 도시이다.','https://ko.wikipedia.org/wiki/%EB%B0%94%EC%BF%A0'),
  ('bali','Bali is an Indonesian island and province and the westernmost of the Lesser Sunda Islands. East of Java and west of Lombok, the province includes the island of Bali and a few smaller offshore islands, notably Nusa Penid…','https://en.wikipedia.org/wiki/Bali'),
  ('bandarseri','Bandar Seri Begawan (BSB) is the capital and largest city of Brunei. It is officially a municipal area with an area of 100.','https://en.wikipedia.org/wiki/Bandar_Seri_Begawan'),
  ('bangkok','방콕은 태국의 수도이자 태국에서 가장 큰 도시이다. 공식 명칭은 끄룽텝 마하나콘이며 줄여서 끄룽텝으로도 불린다.','https://ko.wikipedia.org/wiki/%EB%B0%A9%EC%BD%95'),
  ('barcelona','바르셀로나는 스페인에서 두 번째로 큰 도시로, 스페인 동부 지중해 연안 지역부터 프랑스 남쪽 피레네산맥과 접경지역을 아우르는 카탈루냐 지방의 중심 도시이다. 인구는 1,620,343명(2018년)이고 면적은 101.','https://ko.wikipedia.org/wiki/%EB%B0%94%EB%A5%B4%EC%85%80%EB%A1%9C%EB%82%98'),
  ('basel','바젤은 스위스에서 세 번째로 인구가 많은 도시(2013년: 172,091 명)로 바젤슈타트주에 속한다. 인접 도시권을 포함하면 약 69만 명으로 스위스에서 두 번째로 크다.','https://ko.wikipedia.org/wiki/%EB%B0%94%EC%A0%A4'),
  ('beijing','베이징(중국어 간체자: 北京, 병음: Běijīng 듣기 )또는 북경은 중화인민공화국의 수도이며 상하이시에 이어 두 번째로 큰 도시이다. 허베이성으로 둘러싸여 있으며 동쪽으로는 톈진시와 경계를 접한다.','https://ko.wikipedia.org/wiki/%EB%B2%A0%EC%9D%B4%EC%A7%95%EC%8B%9C'),
  ('beppu','벳푸시는 일본 오이타현 중앙부에 있는 시이며 오이타현에서는 두 번째로 인구가 많다.','https://ko.wikipedia.org/wiki/%EB%B2%B3%ED%91%B8%EC%8B%9C'),
  ('berlin','베를린은 독일의 수도로 면적과 인구 면에서 최대 도시이다. 도시 경계 내 인구에 따르면, 인구는 370만 명으로 유럽 연합에서 가장 인구가 많은 도시이다.','https://ko.wikipedia.org/wiki/%EB%B2%A0%EB%A5%BC%EB%A6%B0'),
  ('boracay','보라카이섬(Boracay)은 필리핀의 섬으로 길이는 12km로 총면적은 11km2이며 인구는 약 1만 3,000명이다.','https://ko.wikipedia.org/wiki/%EB%B3%B4%EB%9D%BC%EC%B9%B4%EC%9D%B4%EC%84%AC'),
  ('bordeaux','보르도는 프랑스 남서부에 있는 항구 도시이다. 보르도는 아키텐 레지옹의 주도(主都)이자, 지롱드주의 주도이다.','https://ko.wikipedia.org/wiki/%EB%B3%B4%EB%A5%B4%EB%8F%84'),
  ('boston','보스턴은 미국 매사추세츠주의 주도이며, 미국에서 제일 오래된 도시 중 하나이다. 뉴잉글랜드 중에서도 최대의 도시로, 이 지역의 경제 및 문화 중심지이며, "뉴잉글랜드의 수도"라는 비공식적인 별칭을 갖고 있다.','https://ko.wikipedia.org/wiki/%EB%B3%B4%EC%8A%A4%ED%84%B4'),
  ('bratislava','브라티슬라바는 슬로바키아의 수도이다. 다뉴브강을 끼고 있으며 인구는 약 43만 명이다.','https://ko.wikipedia.org/wiki/%EB%B8%8C%EB%9D%BC%ED%8B%B0%EC%8A%AC%EB%9D%BC%EB%B0%94'),
  ('brisbane','브리즈번(Brisbane)은 오스트레일리아 퀸즐랜드주에서 가장 인구가 많은 도시이자 주도이다. 오스트레일리아 전체에서는 세 번째로 많은 인구를 가진 도시이다.','https://ko.wikipedia.org/wiki/%EB%B8%8C%EB%A6%AC%EC%A6%88%EB%B2%88'),
  ('bruges','브뤼허는 벨기에의 도시다. 구 시가지는 중세의 모습을 간직하고 있으며 유네스코 세계문화유산으로 지정되었다.','https://ko.wikipedia.org/wiki/%EB%B8%8C%EB%A4%BC%ED%97%88'),
  ('brussels','브뤼셀 수도 지역, 줄여서 브뤼셀은 벨기에의 (사실상의) 수도이다. 벨기에의 한복판에 위치한 정치, 경제, 문화, 교통의 중심지이며, 유럽 연합(EU) 본부가 위치해 사실상 유럽 연합의 수도이다.','https://ko.wikipedia.org/wiki/%EB%B8%8C%EB%A4%BC%EC%85%80'),
  ('bucharest','부쿠레슈티는 루마니아의 수도이다. 영어로는 부카레스트라고 한다.','https://ko.wikipedia.org/wiki/%EB%B6%80%EC%BF%A0%EB%A0%88%EC%8A%88%ED%8B%B0'),
  ('budapest','부다페스트는 헝가리의 수도이자 정치·산업·경제·사회·문화의 중심지다. 인구는 180만을 상회하는데 1980년대 중반의 207만보다는 낮은 수치이다.','https://ko.wikipedia.org/wiki/%EB%B6%80%EB%8B%A4%ED%8E%98%EC%8A%A4%ED%8A%B8'),
  ('buenosaires','부에노스아이레스는 아르헨티나의 수도이며 가장 큰 도시이다. 남아메리카 동남부 라플라타강의 하구에 자리한 항구 도시이며, 남아메리카에서 가장 큰 도시 중의 하나이다.','https://ko.wikipedia.org/wiki/%EB%B6%80%EC%97%90%EB%85%B8%EC%8A%A4%EC%95%84%EC%9D%B4%EB%A0%88%EC%8A%A4'),
  ('busan','부산광역시(釜山廣域市)는 대한민국 남동부에 위치한 광역시이다. 대한민국에서 두 번째로 인구가 많은 도시이자 영남권의 중심 도시이며, 대한민국 최대의 해양 도시로서 부산항을 중심으로 해상 무역과 물류 산업이 발달하였다.','https://ko.wikipedia.org/wiki/%EB%B6%80%EC%82%B0%EA%B4%91%EC%97%AD%EC%8B%9C'),
  ('cairns','케언스(Cairns)는 오스트레일리아 퀸즐랜드주의 도시로 퀸즐랜드주 북동부에 위치한다.','https://ko.wikipedia.org/wiki/%EC%BC%80%EC%96%B8%EC%8A%A4'),
  ('cairo','카이로는 이집트와 아랍 연맹의 수도이며, 나일강의 물줄기가 여러 지류로 갈라지기 시작하는 바로 그 지점에 위치하고 있는 아프리카 대륙과 중동 지역 최대의 도시이다. 서기 642년에 건설된 도시로, 인구는 1700만에 달한다.','https://ko.wikipedia.org/wiki/%EC%B9%B4%EC%9D%B4%EB%A1%9C'),
  ('calgary','캘거리는 캐나다 앨버타주에 있는 도시이다. 1988년 동계 올림픽이 이곳에서 열렸다.','https://ko.wikipedia.org/wiki/%EC%BA%98%EA%B1%B0%EB%A6%AC'),
  ('cambridge','케임브리지(Cambridge)는 영국 런던에서 북쪽에 있는 케임브리지셔주의 중심 도시이다. 케임브리지 대학교가 있는 대학 도시이다.','https://ko.wikipedia.org/wiki/%EC%BC%80%EC%9E%84%EB%B8%8C%EB%A6%AC%EC%A7%80'),
  ('cancun','칸쿤은 멕시코 남동부에 있는 해안 도시로서 인구는 2005년 기준으로 526,701명이다. 행정 구역상으로는 킨타나로오주에 속한다.','https://ko.wikipedia.org/wiki/%EC%BA%89%EC%BF%A4'),
  ('capetown','케이프타운은 남아프리카 공화국의 입법 수도이다. 아프리칸스어로는 카앞스탇(Kaapstad), 이카파(iKapa) 라고 부른다.','https://ko.wikipedia.org/wiki/%EC%BC%80%EC%9D%B4%ED%94%84%ED%83%80%EC%9A%B4'),
  ('cappadocia','카파도키아는 튀르키예 중앙아나톨리아 지역에 있는 지역이다. 주로 네브셰히르주, 카이세리주, 악사라이주, 키르셰히르주, 시바스주 및 니데주에 걸쳐 있다.','https://ko.wikipedia.org/wiki/%EC%B9%B4%ED%8C%8C%EB%8F%84%ED%82%A4%EC%95%84'),
  ('cebu','세부는 필리핀 중부 세부주에 있는 도시이다. 세부주의 주도이며, 비사야 제도의 중심지이다.','https://ko.wikipedia.org/wiki/%EC%84%B8%EB%B6%80'),
  ('chengdu','청두시는 중화인민공화국 서남부 쓰촨성의 성도이다. 대왕판다의 서식지 중 하나로, 대왕판다 연구 기지가 청두시에 있다.','https://ko.wikipedia.org/wiki/%EC%B2%AD%EB%91%90%EC%8B%9C'),
  ('chiangmai','치앙마이는 태국 북부에서 가장 크고 문화적으로 중요한 도시이며 태국에서 두 번째로 큰 도시이자 치앙마이 주의 주도이다. 방콕에서 북쪽으로 700km 떨어진 짜오프라야강의 지류인 삥 강 기슭에 있다.','https://ko.wikipedia.org/wiki/%EC%B9%98%EC%95%99%EB%A7%88%EC%9D%B4'),
  ('chicago','시카고는 뉴욕, 로스앤젤레스에 이어 미국에서 3번째로 큰 도시이며, 일리노이주 및 미국 중서부에서 가장 큰 도시로 그 인구는 270만 명이다. 시카고 랜드라고 불리는 이 지역의 광역 도시권은 950만 명의 인구와 함께 미국에서 3번째로 큰 대도시권이다.','https://ko.wikipedia.org/wiki/%EC%8B%9C%EC%B9%B4%EA%B3%A0'),
  ('chongqing','충칭(중국어 간체자: 重庆, 정체자: 重慶, 병음: Chóngqìng) 또는 중경은 중화인민공화국 서부의 직할시이다. 중화인민공화국의 네 개 직할시 중 하나로 유일하게 서부에 위치한다.','https://ko.wikipedia.org/wiki/%EC%B6%A9%EC%B9%AD%EC%8B%9C'),
  ('chuncheon','춘천시(春川市)는 대한민국 강원특별자치도 서부에 있는 시이자 강원특별자치도청 소재지이다. 태백산맥의 서쪽에 위치하며, 영서 지방의 거점 도시이다.','https://ko.wikipedia.org/wiki/%EC%B6%98%EC%B2%9C%EC%8B%9C'),
  ('colombo','콜롬보는 스리랑카의 최대 도시이자 행정·사법 수도(법적인 수도는 스리자야와르데네푸라코테)이다. 명칭의 유래는 싱할라어로 망고 나무가 무성한 해안을 의미하는 Kola-amba-thota에서 유래되었다.','https://ko.wikipedia.org/wiki/%EC%BD%9C%EB%A1%AC%EB%B3%B4'),
  ('copenhagen','코펜하겐은 덴마크의 수도이자 가장 인구가 많은 도시로 도시 지역에 약 140만 명의 인구가 있고, 코펜하겐 광역권에 200만 명이 넘는 인구가 있다. 이 도시는 외레순 해협을 사이에 두고 스웨덴의 말뫼와 분리된 셸란섬과 아마게르섬에 있다.','https://ko.wikipedia.org/wiki/%EC%BD%94%ED%8E%9C%ED%95%98%EA%B2%90'),
  ('cusco','쿠스코는 페루 남동부 쿠스코주에 있는 도시이다. 80km 북서쪽으로 마추 픽추가 있으며, 안데스 산맥 사이의 해발 3,399m에 있다.','https://ko.wikipedia.org/wiki/%EC%BF%A0%EC%8A%A4%EC%BD%94'),
  ('daegu','대구광역시(大邱廣域市)는 대한민국의 동남부인 경북 지역 내륙에 위치한 광역시이다. 조선시대에는 경상감영 소재지로서 경상도의 중심지였다.','https://ko.wikipedia.org/wiki/%EB%8C%80%EA%B5%AC%EA%B4%91%EC%97%AD%EC%8B%9C'),
  ('daejeon','대전광역시(大田廣域市)는 대한민국
충청권의 중남부에 자리한 광역시이다. 면적은 540km², 인구는 145만 명에 달한다.','https://ko.wikipedia.org/wiki/%EB%8C%80%EC%A0%84%EA%B4%91%EC%97%AD%EC%8B%9C'),
  ('dalat','달랏시는 베트남의 럼동성의 성도로 럼비엔고원에 자리하고 있다. 해발 1,500m 고도에 넓이는 393.','https://ko.wikipedia.org/wiki/%EB%8B%AC%EB%9E%8F'),
  ('danang','다낭은 베트남 남중부 지방의 최대 상업 및 항구도시이자 베트남의 다섯 개의 직할시 중 하나이고, 베트남에서 호찌민시, 하노이, 하이퐁에 이어 네 번째로 큰 도시이다. 면적은 11,859.','https://ko.wikipedia.org/wiki/%EB%8B%A4%EB%82%AD'),
  ('delhi','델리, 또는 공식 명칭 델리 국가수도직할구는 인도의 수도권이며, 인도의 상업·공업·정치 중심지의 하나이다. 그곳에는 올드델리와 뉴델리라는 구/신시가지로 나눌 수 있다.','https://ko.wikipedia.org/wiki/%EB%8D%B8%EB%A6%AC'),
  ('doha','도하는 카타르의 수도이자 최대 도시이며, 페르시아만과 접해 있다. 2015년 인구 조사에 따르면 도하의 인구는 95만 6천여 명이다.','https://ko.wikipedia.org/wiki/%EB%8F%84%ED%95%98'),
  ('dubai','두바이는 페르시아만 남동쪽 해안에 위치한 아랍에미리트의 최대 도시이다. 아랍에미리트를 구성하는 7개의 토후국 가운데 하나인 두바이 토후국의 수도이다.','https://ko.wikipedia.org/wiki/%EB%91%90%EB%B0%94%EC%9D%B4'),
  ('dublin','더블린은 아일랜드의 수도이자 최대 도시이다. 영어의 Dublin은 ''검고 낮은 곳''이라는 뜻으로 노르드어 뒤플린(Dyflin)에서 유래했다.','https://ko.wikipedia.org/wiki/%EB%8D%94%EB%B8%94%EB%A6%B0'),
  ('dubrovnik','Dubrovnik, historically also known as Ragusa, is a city in southern Dalmatia, Croatia, by the Adriatic Sea. It is one of the most prominent tourist destinations in the Mediterranean, a seaport and the centre of the Dubr…','https://en.wikipedia.org/wiki/Dubrovnik'),
  ('edinburgh','에든버러 또는 에딘버러는 스코틀랜드의 수도이며, 글래스고 다음으로 큰 도시다. 1437년 스코틀랜드의 수도가 되었으며, 이후 스코틀랜드의 문화, 정치, 교육, 관광의 중심지 역할을 하고 있다.','https://ko.wikipedia.org/wiki/%EC%97%90%EB%93%A0%EB%B2%84%EB%9F%AC'),
  ('florence','피렌체는 이탈리아 토스카나주의 주도이자 가장 인구가 많은 도시로, 2025년 기준 주민 수는 362,353명이다. 또한 같은 이름의 광역시의 중심지이기도 하며, 광역시 전체 인구는 989,460명에 달한다.','https://ko.wikipedia.org/wiki/%ED%94%BC%EB%A0%8C%EC%B2%B4'),
  ('frankfurt','프랑크푸르트 또는 프랑크푸르트암마인은 독일 중서부 헤센주에 위치한 도시이다. 또한 프랑크푸르트암마인은 브란덴부르크주 소재의 도시인 프랑크푸르트 안 데어 오데르와 구분된다.','https://ko.wikipedia.org/wiki/%ED%94%84%EB%9E%91%ED%81%AC%ED%91%B8%EB%A5%B4%ED%8A%B8'),
  ('fukuoka','Fukuoka is a designated city in the Kyushu region of Japan and the capital city of Fukuoka Prefecture. The city is built along the shores of Hakata Bay, and has been a center of international commerce since ancient time…','https://en.wikipedia.org/wiki/Fukuoka'),
  ('gangneung','강릉시(江陵市)는 대한민국 강원특별자치도 동해안 중부에 있는 시이다. 서울과 비슷한 위도에 위치한 영동 지방 최대 도시이다.','https://ko.wikipedia.org/wiki/%EA%B0%95%EB%A6%89%EC%8B%9C'),
  ('geneva','Geneva is the second-most populous city in Switzerland and the most populous in French-speaking Romandy. Situated in the southwest of the country, where the Rhône exits Lake Geneva, it is the capital of the Republic and…','https://en.wikipedia.org/wiki/Geneva'),
  ('geoje','거제시(巨濟市)는 대한민국 경상남도 남해상의 거제도에 있는 시로, 대한민국에서 두 번째로 큰 섬인 거제도, 칠천도, 가조도 등 88개의 섬으로 이루어져 있다. 지심도를 비롯한 거제시의 많은 구역은 한려해상국립공원 내에 속해 있다.','https://ko.wikipedia.org/wiki/%EA%B1%B0%EC%A0%9C%EC%8B%9C'),
  ('ghent','Ghent is a city and a municipality in the East Flanders province of the Flemish Region of Belgium. It is the capital and largest city of the province and the third largest in the country, after Brussels and Antwerp.','https://en.wikipedia.org/wiki/Ghent'),
  ('goa','고아(孤兒)는 양친이 부재한 미성년자를 말한다. 사적인 양육자가 없는 경우 입양 기관이나 가정위탁을 통해 사적인 양육자를 갖게 되거나 보육원에서 성장하기도 한다.','https://ko.wikipedia.org/wiki/%EA%B3%A0%EC%95%84'),
  ('guam','괌은 오세아니아의 미크로네시아 마리아나 제도에 있는 미국의 해외 속령이다. 차모로인들이 약 4000년 전에 이곳에 정착해 원주민이 되었다.','https://ko.wikipedia.org/wiki/%EA%B4%8C'),
  ('guangzhou','광저우는 중화인민공화국 남부 광둥 성의 성도이자, 화난 지역의 전체의 행정 중심 지역이고, 부성급시로서 성에 준하는 권한을 가지고 있다.','https://ko.wikipedia.org/wiki/%EA%B4%91%EC%A0%80%EC%9A%B0%EC%8B%9C'),
  ('guilin','구이린은 중화인민공화국 광시 좡족 자치구의 지급시이다. 카르스트 지형으로 바위의 병풍이 탑처럼 둘러싸여 있으며 그림과 같은 아름다운 풍경을 타고난 세계적인 관광지이다.','https://ko.wikipedia.org/wiki/%EA%B5%AC%EC%9D%B4%EB%A6%B0%EC%8B%9C'),
  ('gwangju','광주광역시(光州廣域市)는 대한민국 서남쪽에 위치한 광역시였다. 2026년 7월 1일 전남광주통합특별시 설치로 전라남도와 함께 통폐합되었다.','https://ko.wikipedia.org/wiki/%EA%B4%91%EC%A3%BC%EA%B4%91%EC%97%AD%EC%8B%9C'),
  ('gyeongju','경주시(慶州市)는 대한민국 경상북도 동남부에 있는 시이다. 시청 소재지는 동천동이고, 행정구역은 4읍 8면 10동이다.','https://ko.wikipedia.org/wiki/%EA%B2%BD%EC%A3%BC%EC%8B%9C'),
  ('hakodate','하코다테시는 일본 홋카이도 남부에 있는 시이다. 홋카이도에서는 삿포로시, 아사히카와시에 이어 3번째로 인구가 많으며, 중핵시로 지정되어 있다.','https://ko.wikipedia.org/wiki/%ED%95%98%EC%BD%94%EB%8B%A4%ED%85%8C%EC%8B%9C'),
  ('hakone','하코네정은 일본 가나가와현 서부 아시가라시모군의 마을이다.','https://ko.wikipedia.org/wiki/%ED%95%98%EC%BD%94%EB%84%A4%EC%A0%95'),
  ('halong','할롱만 또는 하롱베이는 베트남 북부, 꽝닌성 통킹만 북서부에 있는 만의 명칭이며, 크고 작은 3,000개의 기암괴석과 섬들이 존재한다. 1994년에 유네스코의 세계자연유산으로 지정되었다.','https://ko.wikipedia.org/wiki/%ED%95%A0%EB%A1%B1%EB%A7%8C'),
  ('hamburg','Hamburg, officially the Free and Hanseatic City of Hamburg, is the second-largest city in Germany after Berlin and sixth-largest city in the European Union, with a population of over 1.9 million.','https://en.wikipedia.org/wiki/Hamburg'),
  ('hangzhou','항저우는 장강 삼각주 지역에 자리 잡고 있는 중화인민공화국 저장성의 성도, 지급시, 부성급시다. 상하이에서 180km 가량 떨어져 있으며, 고속열차로 약 1시간 거리에 있다.','https://ko.wikipedia.org/wiki/%ED%95%AD%EC%A0%80%EC%9A%B0%EC%8B%9C'),
  ('hanoi','하노이는 베트남의 수도다. 역대 왕조가 왕도를 정했던 도시로, 홍강 삼각주, 홍강 서편에 위치한다.','https://ko.wikipedia.org/wiki/%ED%95%98%EB%85%B8%EC%9D%B4'),
  ('harbin','하얼빈은 부성급시이자 중국 헤이룽장성의 성도이다. 쑹화강 남쪽 기슭에 자리 잡고 있는 공업 도시이다.','https://ko.wikipedia.org/wiki/%ED%95%98%EC%96%BC%EB%B9%88%EC%8B%9C'),
  ('helsinki','헬싱키는 핀란드의 수도로, 핀란드 남부 핀란드만 연안에 위치해 있다. 에스포, 반타, 카우니아이넨과 함께 핀란드의 수도권을 형성한다.','https://ko.wikipedia.org/wiki/%ED%97%AC%EC%8B%B1%ED%82%A4'),
  ('himeji','히메지시는 일본 효고현 남서부에 있는 시이다. 1996년에 중핵시로 지정되었다.','https://ko.wikipedia.org/wiki/%ED%9E%88%EB%A9%94%EC%A7%80%EC%8B%9C'),
  ('hiroshima','히로시마시는 일본 히로시마현의 도시로, 현청 소재지이다. 일본에서 11번째로 인구가 많은 도시이며, 1974년에는 인구가 80만 명을 넘어 정령지정도시 지정을 요구해 온 결과 1980년 4월 1일에 정령지정도시로 지정되었다.','https://ko.wikipedia.org/wiki/%ED%9E%88%EB%A1%9C%EC%8B%9C%EB%A7%88%EC%8B%9C'),
  ('hobart','호바트(Hobart)는 오스트레일리아 태즈메이니아주의 주도이다.','https://ko.wikipedia.org/wiki/%ED%98%B8%EB%B0%94%ED%8A%B8'),
  ('hochiminh','호찌민, 1890년 5월 19일~1969년 9월 2일)은 베트남의 공산주의 혁명가이자 독립운동가, 정치인, 초대 국가주석이다. 원래 이름은 응우옌신꿍.','https://ko.wikipedia.org/wiki/%ED%98%B8%EC%B0%8C%EB%AF%BC'),
  ('hoian','호이안은 베트남 다낭의 프엉이다. 이는 2025년의 개편에 따른 다낭시의 94개 신설 프엉, 싸, 특구 중 하나이다.','https://ko.wikipedia.org/wiki/%ED%98%B8%EC%9D%B4%EC%95%88'),
  ('hongkong','중화인민공화국 홍콩 특별행정구 줄여서 홍콩은 중화인민공화국 화난 주강 삼각주 동쪽에 위치한 특별행정구이다. 홍콩은 마카오, 광저우, 선전, 주하이, 그리고 광둥성의 다른 주요 도시들과 함께 세계에서 가장 인구가 많은 주강 삼각주 대도시권을 형성하고 있다.','https://ko.wikipedia.org/wiki/%ED%99%8D%EC%BD%A9'),
  ('honolulu','호놀룰루는 미국의 50번째 주인 하와이주의 주도이다. 호놀룰루라는 이름은 하와이어로 보호받는 곳(쉼터, place of shelter)을 의미한다.','https://ko.wikipedia.org/wiki/%ED%98%B8%EB%86%80%EB%A3%B0%EB%A3%A8'),
  ('huahin','후아힌은 태국 서부 쁘라쭈압키리칸 주에서 가장 큰 도시로 후아힌 군의 행정 중심지이다. 태국의 북부 말레이 반도에서 해변 휴양지로 이름이 높다.','https://ko.wikipedia.org/wiki/%ED%9B%84%EC%95%84%ED%9E%8C'),
  ('hue','후에는 베트남 중부의 중앙직할시이다.','https://ko.wikipedia.org/wiki/%ED%9B%84%EC%97%90'),
  ('incheon','인천광역시(仁川廣域市)는 남동쪽으로 시흥시, 북쪽으로 김포시와 접한 광역시이다.
인천항과 인천국제공항을 중심으로 제조업과 물류, 산업이 발달하였다.','https://ko.wikipedia.org/wiki/%EC%9D%B8%EC%B2%9C%EA%B4%91%EC%97%AD%EC%8B%9C'),
  ('innsbruck','인스브루크(Innsbruck)는 오스트리아 티롤주의 주도이다. 알프스의 풍경과 경치가 아름다운 곳으로 서유럽에서 가장 인기있는 겨울 스포츠 관광지이다.','https://ko.wikipedia.org/wiki/%EC%9D%B8%EC%8A%A4%EB%B8%8C%EB%A3%A8%ED%81%AC'),
  ('interlaken','인터라켄은 스위스 베른주에 위치한 도시로, 면적은 4.3km2, 높이는 568m, 인구는 5,429명(2010년 기준), 인구 밀도는 1,234명/km2이다.','https://ko.wikipedia.org/wiki/%EC%9D%B8%ED%84%B0%EB%9D%BC%EC%BC%84'),
  ('istanbul','이스탄불은 튀르키예의 최대 도시이자, 옛 수도다. 행정 구역상 이스탄불주에 속해 있다.','https://ko.wikipedia.org/wiki/%EC%9D%B4%EC%8A%A4%ED%83%84%EB%B6%88'),
  ('jaipur','자이푸르는 인도 라자스탄 주의 주도로서 도로와 철도 등 교통망이 정비된 상공업 중심지이다. 18세기에 건설된 사각형의 계획도시로 거리 전체가 분홍색이라‘분홍 도시’로도 알려져 있는 곳이다.','https://ko.wikipedia.org/wiki/%EC%9E%90%EC%9D%B4%ED%91%B8%EB%A5%B4'),
  ('jakarta','자카르타는 인도네시아의 수도이자 최대 도시이다. 정식 명칭은 자카르타 특수지역이다.','https://ko.wikipedia.org/wiki/%EC%9E%90%EC%B9%B4%EB%A5%B4%ED%83%80'),
  ('jeonju','전주시(全州市)는 대한민국 전북특별자치도 내륙에 위치한 시이자 전북특별자치도청 소재지이다. 대부분의 지역이 완주군에 둘러싸여 있으며, 서쪽으로는 김제시, 서북쪽으로는 익산시와 접한다.','https://ko.wikipedia.org/wiki/%EC%A0%84%EC%A3%BC%EC%8B%9C'),
  ('jiufen','주펀(九份)은 타이완 북부 신베이시 루이팡구에 있는 마을이다. 해안을 마주하고 있는 산맥 위에 지어져 있다.','https://ko.wikipedia.org/wiki/%EC%A3%BC%ED%8E%80'),
  ('kagoshima','Kagoshima , is the capital city of Kagoshima Prefecture, Japan. As of 31 July 2024, the city had an estimated population of 583,966 in 285,992 households, and a population density of 1100 persons per km2.','https://en.wikipedia.org/wiki/Kagoshima'),
  ('kamakura','Kamakura , officially Kamakura City , is a city of Kanagawa Prefecture in Japan. It is located in the Kantō region on the island of Honshu.','https://en.wikipedia.org/wiki/Kamakura'),
  ('kanazawa','가나자와시는 일본 이시카와현의 현청 소재지이다. 이시카와현의 중앙에 위치하며 1996년 4월 1일에 중핵시로 지정되었다.','https://ko.wikipedia.org/wiki/%EA%B0%80%EB%82%98%EC%9E%90%EC%99%80%EC%8B%9C'),
  ('kanchanaburi','깐짜나부리는 태국 서부의 읍(테사반 므앙)이자 깐짜나부리주의 수도이다. 인구는 2002년 기준으로 885,112명이다.','https://ko.wikipedia.org/wiki/%EA%B9%90%EC%A7%9C%EB%82%98%EB%B6%80%EB%A6%AC'),
  ('kandy','Kandy is a major city located in the Central Province of Sri Lanka. It was the last capital of the Sinhalese monarchy from 1469 to 1818, under the Kingdom of Kandy.','https://en.wikipedia.org/wiki/Kandy'),
  ('kaohsiung','가오슝시는 대만 남부에 위치한 도시이다. 2019년 기준 약 2백70만명으로 타이완에서 세번째 규모이다.','https://ko.wikipedia.org/wiki/%EA%B0%80%EC%98%A4%EC%8A%9D%EC%8B%9C'),
  ('kathmandu','카트만두는 네팔의 수도로 네팔에서 가장 큰 도시이다. 네팔 중앙의 카트만두 계곡에 위치하고 있으며, 인구는 약 320만 명이다.','https://ko.wikipedia.org/wiki/%EC%B9%B4%ED%8A%B8%EB%A7%8C%EB%91%90'),
  ('kenting','Kenting National Park, commonly known as Kenting, is a national park located on the Hengchun Peninsula of Pingtung County, Taiwan, covering Hengchun, Checheng, and Manzhou Townships. Established on 1 January 1984, it is…','https://en.wikipedia.org/wiki/Kenting_National_Park'),
  ('kobe','고베시는 일본에서 6번째로 큰 도시로 효고현의 현청 소재지이자 일본을 대표하는 항만 도시로 인구는 약 150만 명이다. 긴키 지방에 위치하고 게이한신 도시권의 일부이다.','https://ko.wikipedia.org/wiki/%EA%B3%A0%EB%B2%A0%EC%8B%9C'),
  ('kohsamui','사무이섬은 태국 끄라 지협 동해안 수랏타니 주의 섬이다. 이 지방 사람들은 간단히 줄여서 ‘사무이’라고 부른다.','https://ko.wikipedia.org/wiki/%EC%82%AC%EB%AC%B4%EC%9D%B4%EC%84%AC'),
  ('kotakinabalu','코타키나발루는 말레이시아 사바주의 주도로, 말레이시아 동부 보르네오섬 최대의 도시이다. 인구는 약 60만명이다.','https://ko.wikipedia.org/wiki/%EC%BD%94%ED%83%80%ED%82%A4%EB%82%98%EB%B0%9C%EB%A3%A8'),
  ('krabi','끄라비는 안다만해로 흘러들어가는 끄라비강의 어귀에 있는 태국 남부의 서쪽 해안에 위치한 끄라비 테사반 므앙(thesaban mueang, town)이다. 2005년을 기준으로 이곳에는 24,986명의 인구가 있다.','https://ko.wikipedia.org/wiki/%EB%81%84%EB%9D%BC%EB%B9%84'),
  ('krakow','크라쿠프는 폴란드 마워폴스카주의 주도이며, 비스와강에 접한 하항이다. 17세기 초반에 바르샤바로 수도를 옮길 때까지 폴란드-리투아니아 연방의 수도였다.','https://ko.wikipedia.org/wiki/%ED%81%AC%EB%9D%BC%EC%BF%A0%ED%94%84'),
  ('kualalumpur','쿠알라룸푸르, 공식적으로 쿠알라룸푸르 연방 직할구는 말레이시아의 수도이다. 말레이시아에서 가장 큰 도시로 면적은 243km2 이며, 2024년 기준 인구는 약 2,075,600명이다.','https://ko.wikipedia.org/wiki/%EC%BF%A0%EC%95%8C%EB%9D%BC%EB%A3%B8%ED%91%B8%EB%A5%B4'),
  ('kumamoto','Kumamoto is the capital city of Kumamoto Prefecture on the island of Kyushu, Japan. As of June 1, 2019, the city had an estimated population of 738,907 and a population density of 1,893 people per km2.','https://en.wikipedia.org/wiki/Kumamoto'),
  ('kyoto','교토는 일본의 역사적인 도시다. 미야코, 교라고도 불렸다.','https://ko.wikipedia.org/wiki/%EA%B5%90%ED%86%A0'),
  ('langkawi','랑카위는 안다만해에 위치한 군도로, 말레이시아 본토의 북서쪽에서 약 30 km 떨어진 곳에 위치한다. 랑카위는 말레이시아 케다 주에 속해 있지만 태국 국경과도 맞닿아 있다.','https://ko.wikipedia.org/wiki/%EB%9E%91%EC%B9%B4%EC%9C%84'),
  ('lapaz','라파스는 볼리비아의 행정 수도이다. 1548년 에스파냐의 알론소 데 멘도사 선장이 건설했다.','https://ko.wikipedia.org/wiki/%EB%9D%BC%ED%8C%8C%EC%8A%A4'),
  ('lasvegas','라스베이거스 또는 라스베가스는 미국 남서부 네바다주 남부 사막 가운데에 있는 도시이자 최대 도시이다. 클라크군에 위치해 있다.','https://ko.wikipedia.org/wiki/%EB%9D%BC%EC%8A%A4%EB%B2%A0%EC%9D%B4%EA%B1%B0%EC%8A%A4'),
  ('lijiang','리장은 중화인민공화국 윈난성의 다리 나시족의 왕도이며, 현재에도 나시족 사람들의 대부분이 이곳에 거주하고 있다. 또한 나시족 이외에도 라후족, 푸미족, 바이족, 이족이 거주하고 있으며, 한족보다 소수민족의 인구가 많은 지역이다.','https://ko.wikipedia.org/wiki/%EB%A6%AC%EC%9E%A5%EC%8B%9C'),
  ('lima','Lima is the capital and largest city of Peru, as well as a primate city. It is located in the valleys of the Chillón, Rímac and Lurín Rivers, in the desert zone of the central coastal part of the country, overlooking th…','https://en.wikipedia.org/wiki/Lima'),
  ('lisbon','Lisbon is the capital and most populous city of Portugal, with an estimated population of 658,236 as of 2025, within its administrative limits and 3,353,000 within the metropolis, as of 2025. The city lies in the wester…','https://en.wikipedia.org/wiki/Lisbon'),
  ('london','런던은 영국과 잉글랜드의 수도이자 최대 도시이다. 인구는 2014년 기준 8,538,689명으로 영국은 물론 유럽 전체 대도시권 중 가장 큰 권역이다.','https://ko.wikipedia.org/wiki/%EB%9F%B0%EB%8D%98'),
  ('losangeles','로스앤젤레스는 미국 캘리포니아주의 남부에 위치한 대도시로, 총면적은 1,299.01km2이다.','https://ko.wikipedia.org/wiki/%EB%A1%9C%EC%8A%A4%EC%95%A4%EC%A0%A4%EB%A0%88%EC%8A%A4'),
  ('luangprabang','루앙프라방 또는 루앙파방은 라오스 북부에 위치한 고대 도시이다. 도시 자체가 세계문화유산으로 유네스코의 세계유산(루앙프라방의 도시)에 등록되어 있다.','https://ko.wikipedia.org/wiki/%EB%A3%A8%EC%95%99%ED%94%84%EB%9D%BC%EB%B0%A9'),
  ('lyon','Lyon is a city in France. It is located at the confluence of the rivers Rhône and Saône, to the northwest of the French Alps, 391 km (243 mi) southeast of Paris, 278 km (173 mi) north of Marseille, and 113 km (70 mi) so…','https://en.wikipedia.org/wiki/Lyon'),
  ('macau','중화인민공화국 마카오 특별행정구 또는 줄여서 마카오는 중화인민공화국의 특별행정구이다. 가까운 도시로는 주하이가 있다.','https://ko.wikipedia.org/wiki/%EB%A7%88%EC%B9%B4%EC%98%A4'),
  ('madrid','Madrid is the capital and most populous city of Spain. It had a population of over 3.','https://en.wikipedia.org/wiki/Madrid'),
  ('male','말레는 몰디브 공화국의 수도이자 섬의 이름이다. 말레는 몰디브에서 가장 인구가 많은 도시이고, 마할이라고도 불린다.','https://ko.wikipedia.org/wiki/%EB%A7%90%EB%A0%88'),
  ('manchester','Manchester is a city in North West England, at the centre of the eponymous county of Greater Manchester. It had a population of over 589,000 in 2024.','https://en.wikipedia.org/wiki/Manchester'),
  ('manila','Manila, officially the City of Manila, is the capital and second-most populous city of the Philippines after Quezon City. According to the 2024 census, it has a population of 1,902,590 people.','https://en.wikipedia.org/wiki/Manila'),
  ('marrakech','마라케시는 모로코 중앙부에 있는 도시이다. 인구는 1,036,500명(2006년)이다.','https://ko.wikipedia.org/wiki/%EB%A7%88%EB%9D%BC%EC%BC%80%EC%8B%9C'),
  ('matsuyama','마쓰야마시는 일본 에히메현 중부에 있는 시이자 에히메현의 현청 소재지이다. 인구는 약 50만 명으로 시코쿠에서 가장 인구가 많은 도시이다.','https://ko.wikipedia.org/wiki/%EB%A7%88%EC%93%B0%EC%95%BC%EB%A7%88%EC%8B%9C'),
  ('melbourne','Melbourne is the capital and most populous city of the Australian state of Victoria and the second-most populous city in Australia. The city''s name generally refers to a 9,993-square-kilometre (3,858 sq mi) area, compri…','https://en.wikipedia.org/wiki/Melbourne'),
  ('mexicocity','멕시코시티는 멕시코의 수도로, 멕시코 고원 위에 위치해 있다. 아스텍 제국 시대에는 텍스코코호 위의 섬에 있는 테노치티틀란이라는 도시였는데, 스페인 사람들이 호수를 메워 멕시코시티를 건설했다.','https://ko.wikipedia.org/wiki/%EB%A9%95%EC%8B%9C%EC%BD%94%EC%8B%9C%ED%8B%B0'),
  ('miami','마이애미는 플로리다주의 도시로 주에서 가장 인구가 많은 카운티 마이애미데이드군의 군청 소재지이다. 409,719명 이상의 인구와 함께 마이애미는 5.','https://ko.wikipedia.org/wiki/%EB%A7%88%EC%9D%B4%EC%95%A0%EB%AF%B8'),
  ('milan','밀라노는 이탈리아의 북부에 있는 도시로, 롬바르디아주의 주도이다. 밀라노는 이탈리아 북부의 최대 도시로, 롬바르디아 평원에 위치하고 있으며, 포강이 이 도시를 흐르고 있다.','https://ko.wikipedia.org/wiki/%EB%B0%80%EB%9D%BC%EB%85%B8'),
  ('miyakojima','Miyako Island is the largest and the most populous island among the Miyako Islands of Okinawa Prefecture, Japan. Miyako Island is administered as part of the City of Miyako Island, which includes not only Miyako Island,…','https://en.wikipedia.org/wiki/Miyako_Island'),
  ('mokpo','목포(木浦, Mokpo)는 대한민국 전남광주통합특별시 서남부의 무안반도 남단에 있는 시이다. 순천시, 여수시에 이어 전남에서 세번째로 큰 도시로, 영산강 하구에 위치하며 남쪽은 영산강을 경계로 영암군 삼호읍과 마주하고, 북쪽과 동쪽은 무안군 삼향읍에 둘러싸여 있다.','https://ko.wikipedia.org/wiki/%EB%AA%A9%ED%8F%AC%EC%8B%9C'),
  ('montreal','Montreal is the largest city in the province of Quebec, the second-largest in Canada, and the eighth-largest in North America. Founded in 1642 as Ville-Marie, or "City of Mary", it now takes its name from Mount Royal, t…','https://en.wikipedia.org/wiki/Montreal'),
  ('mumbai','Mumbai, also known as Bombay, is the capital city of the Indian state of Maharashtra. It is the financial capital and the most populous city proper of India, with an estimated population of 12.','https://en.wikipedia.org/wiki/Mumbai'),
  ('munich','뮌헨은 독일 바이에른주의 최대 도시이자 주도시이다. 이 도시는 알프스 북부의 이자르강가에 위치한다.','https://ko.wikipedia.org/wiki/%EB%AE%8C%ED%97%A8'),
  ('nagasaki','나가사키시는 일본 규슈 북서부, 나가사키현 남서부에 있는 도시이다. 나가사키현의 현청 소재지이자 최대 도시이며 중핵시로 지정되어 있다.','https://ko.wikipedia.org/wiki/%EB%82%98%EA%B0%80%EC%82%AC%ED%82%A4%EC%8B%9C'),
  ('nagoya','나고야시는 일본 아이치현 서부에 있는 도시로, 아이치현의 현청 소재지이자 주부 지방의 중심 도시이다. 정령지정도시로 지정되어 있다.','https://ko.wikipedia.org/wiki/%EB%82%98%EA%B3%A0%EC%95%BC%EC%8B%9C'),
  ('nairobi','나이로비는 케냐의 수도이자 가장 큰 도시이다. 나이로비는 케냐 중남부에 있으며 해발 1,795 m 높이에 있다.','https://ko.wikipedia.org/wiki/%EB%82%98%EC%9D%B4%EB%A1%9C%EB%B9%84'),
  ('naples','Naples is the regional capital of Campania, southern Italy. With a population of 905,050 within the city''s administrative limits as of 2026, it is the largest city in southern Italy and the third-largest city in Italy a…','https://en.wikipedia.org/wiki/Naples'),
  ('nara','정치지리학에서 나라 또는 국(國), 방(邦)은 일정한 영토와 거기에 사는 사람들로 구성된 지리적 단위를 일컫는다. 정치학에서 ''국가''라는 용어가 주로 주권국을 일컫는 것과 달리, 정치지리학적에서 ''나라''는 주권국 외에도 다른 땅과 지리적으로 구분되는 영토와 사람들로 구성된 단위를 일컬을 수도 있다.','https://ko.wikipedia.org/wiki/%EB%82%98%EB%9D%BC'),
  ('nashville','Nashville is the capital and most populous city in the U.S.','https://en.wikipedia.org/wiki/Nashville%2C_Tennessee'),
  ('neworleans','New Orleans is a consolidated city-parish located along the Mississippi River in the U.S.','https://en.wikipedia.org/wiki/New_Orleans'),
  ('newyork','뉴욕 또는 뉴욕시는 미국의 북동부, 뉴욕주의 남쪽 끝에 있는 도시이자 미국에서 가장 인구가 많은 도시이자 전 세계에서 가장 인구가 많은 도시 중 하나이자 미국의 최대 도시이다. 세계적인 대도시인 뉴욕은 상업, 금융, 미디어, 예술, 패션, 연구, 기술, 교육, 엔터테인먼트 등 많은 분야에 걸쳐 큰 영향을 끼치고 있으며, 도쿄, 런던과 함께 세계적인 글로벌 도시이자 세계의 문화 수도로 불리기…','https://ko.wikipedia.org/wiki/%EB%89%B4%EC%9A%95'),
  ('nice','Nice is a city located in the prefecture of the Alpes-Maritimes department in France. The Nice agglomeration extends beyond the administrative city limits, with a population of nearly one million over an area of approxi…','https://en.wikipedia.org/wiki/Nice'),
  ('nikko','닛코시는 일본 도치기현에 있는 시이다. 도쿄에서 북쪽으로 약 140km, 우쓰노미야시에서 서쪽으로 약 35km 떨어져 있고 도쿠가와 이에야스의 능이 있는 닛코 동조궁과 767년에 세워진 후타라산 신사가 있는 일본과 해외 관광객들에게 인기 있는 관광지이다.','https://ko.wikipedia.org/wiki/%EB%8B%9B%EC%BD%94%EC%8B%9C'),
  ('oaxaca','Oaxaca, officially the Free and Sovereign State of Oaxaca, is one of the 31 states of Mexico. It is divided into 570 municipalities, of which 418 are governed by the system of usos y costumbres with recognized local for…','https://en.wikipedia.org/wiki/Oaxaca'),
  ('okinawa','오키나와현은 일본 최남단에 있는 현으로, 류큐 열도 중에 이오토리섬 및 북위 27도 이남에 속하는 섬들과 다이토 제도를 관할한다. 현청 소재지는 오키나와섬의 가장 큰 도시인 나하시(那覇市)이다.','https://ko.wikipedia.org/wiki/%EC%98%A4%ED%82%A4%EB%82%98%EC%99%80%ED%98%84'),
  ('orlando','올랜도(Orlando)는 미국 플로리다주에 있는 도시이다. 인구는 2010년 조사 기준 238,300명.','https://ko.wikipedia.org/wiki/%EC%98%AC%EB%9E%9C%EB%8F%84'),
  ('osaka','오사카는 일본 긴키 지방의 지명이다. 현재의 오사카라는 지명은 긴키 지방에 위치하는 광역자치단체인 오사카부, 또는 그 부청 소재지이자 서일본 최대의 시정촌 도시인 오사카시를 가리키고, 넓은 의미로는 오사카시를 중심으로 하는 게이한신을 의미한다.','https://ko.wikipedia.org/wiki/%EC%98%A4%EC%82%AC%EC%B9%B4'),
  ('oslo','오슬로(Oslo)는 노르웨이의 남부 해안에 있는 도시이자 노르웨이의 수도이다. 1048년에 바이킹 왕 하랄드 3세에 의해 건설되었다.','https://ko.wikipedia.org/wiki/%EC%98%A4%EC%8A%AC%EB%A1%9C'),
  ('otaru','오타루시는 일본 홋카이도 서부 시리베시 종합진흥국 관내에 있는 시이다.','https://ko.wikipedia.org/wiki/%EC%98%A4%ED%83%80%EB%A3%A8%EC%8B%9C'),
  ('oxford','Oxford is a cathedral city and non-metropolitan district in Oxfordshire, England, of which it is the county town.','https://en.wikipedia.org/wiki/Oxford'),
  ('palawan','팔라완섬(Palawan Island)은 필리핀 남서부에 있는 섬으로, 민도로섬과 보르네오섬(말레이시아) 사이에 있다.','https://ko.wikipedia.org/wiki/%ED%8C%94%EB%9D%BC%EC%99%84%EC%84%AC'),
  ('palermo','팔레르모는 이탈리아 남부 시칠리아섬에 있는 도시로, 인구는 654,121명(2011년 기준)이다. 시칠리아주의 주도이며, 티레니아해에 면하는 항구도시이다.','https://ko.wikipedia.org/wiki/%ED%8C%94%EB%A0%88%EB%A5%B4%EB%AA%A8'),
  ('pamukkale','파묵칼레(Pamukkale)는 튀르키예 남서부 데니즐리 주 데니즐리에 위치한 석회붕을 말한다. 파묵칼레의 뜻은 튀르키예어로 파묵이 목화를 뜻하고 칼레는 성을 뜻하므로 목화 성이란 뜻이다.','https://ko.wikipedia.org/wiki/%ED%8C%8C%EB%AC%B5%EC%B9%BC%EB%A0%88'),
  ('paris','Paris is the capital and largest city of France, with an estimated city population of 2.04 million in an area of 105.','https://en.wikipedia.org/wiki/Paris'),
  ('pattaya','파타야는 태국 타이만 동쪽 촌부리주에 있는 동남아시아의 유명한 휴양지이자 해안 도시다. 방콕에서 남동쪽으로 약 145 km 떨어져 있다.','https://ko.wikipedia.org/wiki/%ED%8C%8C%ED%83%80%EC%95%BC'),
  ('penang','풀라우피낭주, 간단히 피낭주 또는 페낭주는 말레이시아를 구성하는 13개의 주 가운데 하나로, 프를리스주 다음으로 말레이시아에서 두 번째로 면적이 작은 주이며 말레이시아에서 여덟 번째로 인구가 많은 주이다. 주도는 조지타운이며 인구는 1,520,143명(2010년 기준), 면적은 1,048km2, 인구밀도는 1,450.','https://ko.wikipedia.org/wiki/%ED%8E%98%EB%82%AD%EC%A3%BC'),
  ('perth','퍼스는 오스트레일리아 웨스턴오스트레일리아주의 주도이다. 오스트레일리아에서 네 번째로 큰 도시로, 인구는 2007년을 기준으로 155만 명이며, 퍼스 시의 경우 90만 명이 거주하고 있다.','https://ko.wikipedia.org/wiki/%ED%8D%BC%EC%8A%A4'),
  ('petra','페트라는 요르단의 고대 유적이다. 바위를 깎아 만든, 암벽에 세워진 도시로 페트라라는 뜻은 바위를 뜻한다.','https://ko.wikipedia.org/wiki/%ED%8E%98%ED%8A%B8%EB%9D%BC'),
  ('philadelphia','필라델피아 시는 펜실베이니아주에서 가장 큰 도시로, 미국 독립시기인 18세기에 미국의 수도였다. 현재는 미국 북동부에서 두 번째로 큰 도시이자 미국 전체에서 다섯 번째로 큰 도시이다.','https://ko.wikipedia.org/wiki/%ED%95%84%EB%9D%BC%EB%8D%B8%ED%94%BC%EC%95%84'),
  ('phnompenh','프놈펜은 캄보디아의 수도이자, 행정, 경제, 문화의 중심지로 캄보디아 최대의 도시이다.','https://ko.wikipedia.org/wiki/%ED%94%84%EB%86%88%ED%8E%9C'),
  ('phuket','Phuket is one of the southern provinces (changwat) of Thailand. It consists of the island of Phuket, the country''s largest island, and another 32 smaller islands off its coast.','https://en.wikipedia.org/wiki/Phuket_province'),
  ('phuquoc','푸꾸옥은 베트남 남서부에 위치한 섬으로 타이만과 접하며 행정 구역상으로는 안장성 푸꾸옥 특구라고 명명된다. 베트남에서 가장 큰 섬으로 섬의 면적은 575 km2이고, 인구는 2025 현재 기준으로 약 157,629명이다.','https://ko.wikipedia.org/wiki/%ED%91%B8%EA%BE%B8%EC%98%A5'),
  ('pisa','피사는 이탈리아 토스카나주에 있는 도시이다. 피사도의 현청 소재지이며, 시의 인구는 약 9만명이다.','https://ko.wikipedia.org/wiki/%ED%94%BC%EC%82%AC'),
  ('pohang','Pohang is the largest city in North Gyeongsang Province, South Korea, with a population of 499,363 as of 2022, bordering the East Sea to the east, Yeongcheon to the west, Gyeongju to the south, and Cheongsong and Yeongd…','https://en.wikipedia.org/wiki/Pohang'),
  ('pokhara','포카라 는 네팔의 수도인 카트만두에서 서쪽으로 약 200 km 떨어진 곳에 위치한 도시로 약 19만 명의 주민이 살고 있어 네팔에서 두 번째로 큰 도시로 꼽힌다.','https://ko.wikipedia.org/wiki/%ED%8F%AC%EC%B9%B4%EB%9D%BC'),
  ('porto','포르투는 포르투갈 북부의 항구 도시로 포르투갈 제2의 도시이다. 면적은 약 42km2, 인구는 약 231,800명 (2021).','https://ko.wikipedia.org/wiki/%ED%8F%AC%EB%A5%B4%ED%88%AC'),
  ('prague','프라하는 체코의 수도이다. 인구는 약 128만 명이며, 광역도시권을 모두 포함하면 인구는 약 216만 명에 달한다.','https://ko.wikipedia.org/wiki/%ED%94%84%EB%9D%BC%ED%95%98'),
  ('qingdao','Qingdao, archaically known as Tsingtao, is a prefecture-level city in the eastern Shandong Province of China. Lying across the Shandong Peninsula and looking out to the Yellow Sea, it borders the prefecture-level cities…','https://en.wikipedia.org/wiki/Qingdao'),
  ('reykjavik','레이캬비크는 아이슬란드의 수도이며 대표적인 도시이다. 항구 도시이며 레이캬비크 고등학교가 있다.','https://ko.wikipedia.org/wiki/%EB%A0%88%EC%9D%B4%EC%BA%AC%EB%B9%84%ED%81%AC'),
  ('rio','리우데자네이루는 브라질 남동부 대서양 연안에 자리한 도시로 리우데자네이루주의 주도이다. 줄여서 리우(Rio, 리오, 히우)라고도 불린다.','https://ko.wikipedia.org/wiki/%EB%A6%AC%EC%9A%B0%EB%8D%B0%EC%9E%90%EB%84%A4%EC%9D%B4%EB%A3%A8'),
  ('riyadh','Riyadh is the capital and largest city of Saudi Arabia. It is also the capital of the Riyadh Province and the centre of the Riyadh Governorate.','https://en.wikipedia.org/wiki/Riyadh'),
  ('rome','로마는 이탈리아의 수도이자 최대 도시로, 라치오주의 주도이며, 테베레강 연안에 있다. 로마시의 행정구역 면적은 1,285.','https://ko.wikipedia.org/wiki/%EB%A1%9C%EB%A7%88'),
  ('saipan','사이판은 전체 115.39 km2의 면적과 함께 서쪽의 태평양(15°10’51”N, 145°45’21”E)에 있는 마리아나 제도에 속하는 15개의 열대 섬이 하나로 늘어선, 북마리아나 제도의 가장 큰 섬이자 수도이다.','https://ko.wikipedia.org/wiki/%EC%82%AC%EC%9D%B4%ED%8C%90%EC%84%AC'),
  ('salzburg','잘츠부르크는 오스트리아 서부에 있는 도시로 잘츠부르크주의 주도이기도 하다. 잘츠부르크는 바로크 양식의 건축과, 다양한 역사, 모차르트의 출생지, 그리고 알프스로의 관문으로 널리 알려져 있다.','https://ko.wikipedia.org/wiki/%EC%9E%98%EC%B8%A0%EB%B6%80%EB%A5%B4%ED%81%AC'),
  ('sanfrancisco','샌프란시스코는 미국 캘리포니아주 북부에 있는 도시로, 북부 캘리포니아의 문화, 경제, 상업 거점 역할을 하고 있다. 공식적인 명칭은 샌프란시스코시군이다.','https://ko.wikipedia.org/wiki/%EC%83%8C%ED%94%84%EB%9E%80%EC%8B%9C%EC%8A%A4%EC%BD%94'),
  ('santiago','Santiago, also known as Santiago de Chile, is the capital and largest city of Chile and one of the largest cities in the Americas. Located in the Chilean Central Valley within the Santiago Basin, between the Andes to th…','https://en.wikipedia.org/wiki/Santiago'),
  ('saopaulo','상파울루는 상파울루주의 수도이자 브라질, 아메리카, 그리고 서반구와 남반구에서 가장 인구 밀도가 높은 도시이다. GaWC에 의해 세계 도시로 분류되며, 상업, 금융, 예술, 엔터테인먼트 분야에서 상당한 국제적 영향력을 행사한다.','https://ko.wikipedia.org/wiki/%EC%83%81%ED%8C%8C%EC%9A%B8%EB%A3%A8'),
  ('sapa','Sa Pa is a district-level town in Lào Cai province in the Northwest region of Vietnam. It covers an area of 685 km2 (264 sq mi) and had a population of 70,663 as of 2022.','https://en.wikipedia.org/wiki/Sa_Pa'),
  ('sapporo','삿포로시는 일본 홋카이도의 도오지방에 위치하고 이시카리 진흥국에 속한 도시로, 홋카이도의 도청 소재지이자 경제 중심지이다. 일본의 정령지정도시 중 하마마쓰시, 시즈오카시 다음으로 면적이 넓고 일본의 도시 중 다섯 번째로 인구가 많다.','https://ko.wikipedia.org/wiki/%EC%82%BF%ED%8F%AC%EB%A1%9C%EC%8B%9C'),
  ('seattle','시애틀은 미국 워싱턴주 킹군의 군청 소재지로 해안 항구 도시이다. 북미 태평양 북서부와 미국 워싱턴주에서 가장 큰 도시로 2019년 기준 753,675명의 인구가 거주하고 있으며, 미국에서 가장 빠르게 인구가 증가하고 있는 대도시이다.','https://ko.wikipedia.org/wiki/%EC%8B%9C%EC%95%A0%ED%8B%80'),
  ('sendai','센다이시는 일본 미야기현의 도시이다. 미야기현의 현청 소재지이고, 도호쿠 지방의 중심 도시이다.','https://ko.wikipedia.org/wiki/%EC%84%BC%EB%8B%A4%EC%9D%B4%EC%8B%9C'),
  ('seoul','서울특별시(서울特別市)는 대한민국의 수도이자 문화·인문·정치·경제 중심지 역할을 하는 도시로, 경기도와 인천광역시까지 아우르는 수도권의 중심지 기능을 하고 있다. 대한민국에서 유일하게 특별시로 지정된 도시이고 종주 도시(제1의 도시) 기능을 하고 있다.','https://ko.wikipedia.org/wiki/%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C'),
  ('seville','세비야는 스페인의 남서부에 있는 도시로, 안달루시아 지방의 예술, 문화, 금융의 중심 도시이며 세비야주의 주도이다. 과달키비르강이 흐르는 평야지대에 자리잡고 있다.','https://ko.wikipedia.org/wiki/%EC%84%B8%EB%B9%84%EC%95%BC'),
  ('shenzhen','Shenzhen is a prefecture-level city in Guangdong, China. A special economic zone, it is located on the east bank of the Pearl River estuary on the central coast of Guangdong, bordering Hong Kong to the south, Dongguan t…','https://en.wikipedia.org/wiki/Shenzhen'),
  ('singapore','싱가포르 또는 공식 명칭 싱가포르 공화국은 동남아시아와, 말레이 반도의 남쪽에 위치한 섬나라이자 항구 도시로 이루어진 도시 국가이다. 서쪽으로는 말라카 해협, 북쪽의 조호르 해협과 남쪽의 싱가포르 해협을 두고 각각 말레이시아, 인도네시아와 약간 분리되어 있다.','https://ko.wikipedia.org/wiki/%EC%8B%B1%EA%B0%80%ED%8F%AC%EB%A5%B4'),
  ('stockholm','스톡홀름은 스웨덴의 스칸디나비아반도 최대 도시이다. 많은 섬을 끼고 있어 "북방의 베네치아"라고도 불린다.','https://ko.wikipedia.org/wiki/%EC%8A%A4%ED%86%A1%ED%99%80%EB%A6%84'),
  ('strasbourg','Strasbourg is a prefecture and commune, and the largest city of the Grand Est region of northeastern France, in the historic region of Alsace. It is the prefecture of the Bas-Rhin department and the official seat of the…','https://en.wikipedia.org/wiki/Strasbourg'),
  ('suncheon','Suncheon is the largest city in Jeonnam-Gwangju, South Korea, with a population of 280,719 as of 2022. It is located in the southeast of the province and is a scenic agricultural and industrial city, known for tourist a…','https://en.wikipedia.org/wiki/Suncheon'),
  ('suzhou','쑤저우시(중국어 정체자: 蘇州市, 간체자: 苏州市, 병음: Sūzhōu)는 중화인민공화국 장쑤성 남동쪽의 타이후 동쪽에 있는 운하 도시이다.','https://ko.wikipedia.org/wiki/%EC%91%A4%EC%A0%80%EC%9A%B0%EC%8B%9C'),
  ('sydney','시드니(Sydney, )는 오스트레일리아의 뉴사우스웨일스주의 주도이자 오스트레일리아의 최대 도시이다. 오세아니아에서 인구가 가장 많은 도시로 알려져 있다.','https://ko.wikipedia.org/wiki/%EC%8B%9C%EB%93%9C%EB%8B%88'),
  ('tahiti','Tahiti is the largest island of the Windward group of the Society Islands in French Polynesia, an overseas collectivity of France. It is a tropical island located in the central part of the Pacific Ocean.','https://en.wikipedia.org/wiki/Tahiti'),
  ('taichung','타이중시는 대만에서 신베이시에 이어 두 번째로 인구가 많은 도시이자 중화민국의 직할시이다. 대만 본도 중서부에 위치하며 북쪽으로는 먀오리현과 신주현, 남쪽으로는 장화현과 난터우현, 동쪽으로는 화롄현과 이란현에 접해 있다.','https://ko.wikipedia.org/wiki/%ED%83%80%EC%9D%B4%EC%A4%91%EC%8B%9C'),
  ('tainan','Tainan, officially Tainan City, is a special municipality in southern Taiwan, facing the Taiwan Strait on its western coast. Tainan is the oldest city on the island and commonly called the "prefectural capital" for its…','https://en.wikipedia.org/wiki/Tainan'),
  ('taipei','타이베이시 또는 타이페이시는 대만섬 북부에 위치한 도시로, 중화민국의 중앙정부 소재지 및 임시(행정)수도이다. 법률상 중화민국의 수도는 난징시이다.','https://ko.wikipedia.org/wiki/%ED%83%80%EC%9D%B4%EB%B2%A0%EC%9D%B4%EC%8B%9C'),
  ('takamatsu','다카마쓰시는 일본 시코쿠 북동부, 가가와현의 거의 중앙에 있는 시이다. 가가와현의 현청 소재지이자 중핵시이며, 세토우치 지방의 항만 도시이다.','https://ko.wikipedia.org/wiki/%EB%8B%A4%EC%B9%B4%EB%A7%88%EC%93%B0%EC%8B%9C'),
  ('tallinn','탈린은 에스토니아의 수도이며, 발트해의 핀란드 만 연안에 있는 항만 도시로서 공업의 중심지이다. 모터·수은 정류기·라디오·굴착기·케이블·직물 등의 공장이 있다.','https://ko.wikipedia.org/wiki/%ED%83%88%EB%A6%B0'),
  ('tashkent','타슈켄트는 우즈베키스탄의 수도이다. 중앙아시아에서 가장 큰 도시로, 2024년 4월 1일 기준 300만 명이 넘는 인구가 거주하고 있으며 우즈베키스탄 북부 카자흐스탄과의 접경 지역에 위치하고 있다.','https://ko.wikipedia.org/wiki/%ED%83%80%EC%8A%88%EC%BC%84%ED%8A%B8'),
  ('tbilisi','트빌리시는 조지아의 수도이다. 도시의 면적은 504.','https://ko.wikipedia.org/wiki/%ED%8A%B8%EB%B9%8C%EB%A6%AC%EC%8B%9C'),
  ('telaviv','텔아비브야파 통칭 텔아비브는 이스라엘 서부 지중해 연안에 있는 도시이다. 이스라엘의 실질적 수도이며, 국제법적 수도이다.','https://ko.wikipedia.org/wiki/%ED%85%94%EC%95%84%EB%B9%84%EB%B8%8C'),
  ('tokyo','도쿄 또는 동경은 일본 혼슈 동부에 있는, 메이지 시대 이후 사실상 일본의 수도이자 최대 도시이다. 행정 구역 상으로는 도쿄도에 속하지만, 도쿄도는 다마 지역이나 이즈 제도, 오가사와라 제도의 넓은 지역을 포함하고 있어서 도시라는 뜻의 "도쿄"와는 그 의미가 조금 다르다.','https://ko.wikipedia.org/wiki/%EB%8F%84%EC%BF%84'),
  ('tongyeong','통영시(統營市)는 대한민국 경상남도 남해안에 있는 시이다. 통영이라는 지명은 선조 37년(1604년) 두룡포로 삼도수군통제영을 옮긴 것에서 유래한다.','https://ko.wikipedia.org/wiki/%ED%86%B5%EC%98%81%EC%8B%9C'),
  ('toronto','토론토는 캐나다에서 가장 큰 도시이며, 북아메리카에서 4번째로 큰 도시이다. 아울러 온타리오주의 주도(州都)이다.','https://ko.wikipedia.org/wiki/%ED%86%A0%EB%A1%A0%ED%86%A0'),
  ('tromso','트롬쇠(Tromsø)는 노르웨이 트롬스주의 주도이다. 2012년 현재 72,066 명의 주민이 있다.','https://ko.wikipedia.org/wiki/%ED%8A%B8%EB%A1%AC%EC%87%A0'),
  ('tulum','Tulum is the site of a pre-Columbian Mayan walled city which served as a major port for Coba, in the Mexican state of Quintana Roo. The ruins are situated on 12-meter-tall (39 ft) cliffs along the east coast of the Yuca…','https://en.wikipedia.org/wiki/Tulum'),
  ('tunis','튀니스는 튀니지의 수도이다. 2008년 기준 인구 120만 명으로 튀니지에서 가장 큰 도시이다.','https://ko.wikipedia.org/wiki/%ED%8A%80%EB%8B%88%EC%8A%A4'),
  ('turin','토리노는 이탈리아 북서부의 산업 도시로 피에몬테주의 주도이자 토리노 광역시의 시청 소재지이다. 포강 서쪽 강변에 자리하고 있으며 알프스산맥과 인접해있다.','https://ko.wikipedia.org/wiki/%ED%86%A0%EB%A6%AC%EB%85%B8'),
  ('ulaanbaatar','울란바타르, 또는 울란바토르는 몽골의 수도이자 최대 도시이다. 몽골어로 ''붉은 영웅''이라는 뜻으로 거주 인구는 2021년 기준으로 약 167만 명이다.','https://ko.wikipedia.org/wiki/%EC%9A%B8%EB%9E%80%EB%B0%94%ED%83%80%EB%A5%B4'),
  ('ulsan','울산광역시(蔚山廣域市)는 대한민국 남동부에 있는 광역시이다. 서쪽으로 경상남도 밀양시, 양산시, 경상북도 청도군, 북쪽으로 경상북도 경주시, 남쪽으로 부산광역시 기장군과 접한다.','https://ko.wikipedia.org/wiki/%EC%9A%B8%EC%82%B0%EA%B4%91%EC%97%AD%EC%8B%9C'),
  ('uyuni','우유니는 볼리비아 남서쪽에 있는 도시다. 우유니는 주로 세계 최대 규모의 소금 사막인 살라르 데 우유니를 방문하는 관광객들의 관문 역할을 하는 도시다.','https://ko.wikipedia.org/wiki/%EC%9A%B0%EC%9C%A0%EB%8B%88'),
  ('valencia','발렌시아는 스페인 발렌시아 주의 주도이다. 인구는 약 81만 명(2008)으로 제지(製紙)·담배·식료품 공업의 중심지이며 마요르카 섬과 함께 보양·관광지로 되어 있다.','https://ko.wikipedia.org/wiki/%EB%B0%9C%EB%A0%8C%EC%8B%9C%EC%95%84'),
  ('valletta','Valletta, also known as Città Umilissima, is the capital city of Malta and one of its 68 council areas. Located between the Grand Harbour to the east and Marsamxett Harbour to the west, its population as of 2021 was 5,1…','https://en.wikipedia.org/wiki/Valletta'),
  ('vancouver','밴쿠버는 캐나다의 브리티시컬럼비아주 남서부에 있는 도시이자 캐나다에서 토론토와 몬트리올을 잇는 세 번째로 큰 도시(광역도시권 기준)이다. 밴쿠버 시와 주변 10여개 조그만 도시들을 모아 메트로 밴쿠버라 부른다.','https://ko.wikipedia.org/wiki/%EB%B0%B4%EC%BF%A0%EB%B2%84'),
  ('varanasi','바라나시, 바나라스 또는 카시는 인도 우타르프라데시주에 위치한 도시로 옛날 카시 왕국의 수도이자 동시에 힌두교의 최대 성지이다. 바라나시를 흐르는 갠지스강은 힌두교도에게 성스러운 젖줄로, 가트에는 강에 몸을 담그고 그 물을 마시기 위해 모여든 신도들로 북적거린다.','https://ko.wikipedia.org/wiki/%EB%B0%94%EB%9D%BC%EB%82%98%EC%8B%9C'),
  ('venice','베네치아는 이탈리아 북부에 위치한 베네토주 베네치아 광역시에 속하는 도시로, 베네토 주의 주도(州都)이다. 영어 명칭인 베니스로도 잘 알려져 있다.','https://ko.wikipedia.org/wiki/%EB%B2%A0%EB%84%A4%EC%B9%98%EC%95%84'),
  ('vienna','Vienna is the capital, most populous city, and one of the nine states of Austria. It is Austria''s primate city, with just over two million inhabitants.','https://en.wikipedia.org/wiki/Vienna'),
  ('vientiane','Vientiane is the capital and largest city of Laos. Comprising the 5 urban districts of Vientiane Prefecture, the city is located on the banks of the Mekong, close to the border with Thailand.','https://en.wikipedia.org/wiki/Vientiane'),
  ('warsaw','바르샤바, 공식적으로 수도 바르샤바(Miasto stołeczne Warszawa)는 폴란드의 수도이자 최대 도시로 폴란드 중동부의 비스와강 연안에 위치한다. 인구는 186만 명이며 대도시권을 포함하면 310만 명으로 유럽 연합 6위이다.','https://ko.wikipedia.org/wiki/%EB%B0%94%EB%A5%B4%EC%83%A4%EB%B0%94'),
  ('xian','Xi''an is the capital of the Chinese province of Shaanxi. A sub-provincial city on the Guanzhong plain, the city is the third-most populous city in Western China after Chongqing and Chengdu, as well as the most populous…','https://en.wikipedia.org/wiki/Xi''an'),
  ('yangon','Yangon, also romanized in English as Rangoon, is the capital city of the Yangon Region and the most populous city of Myanmar. Yangon was the capital city of Myanmar until 2005 and served as such until 2006, when the mil…','https://en.wikipedia.org/wiki/Yangon'),
  ('yeosu','여수시(麗水市)는 대한민국 전남광주통합특별시 동남부 여수반도에 있는 시이다. 면적은 512.','https://ko.wikipedia.org/wiki/%EC%97%AC%EC%88%98%EC%8B%9C'),
  ('yogyakarta','욕야카르타 또는 족자카르타(Jogjakarta), 줄여서 족자(Jogja)는 인도네시아 욕야카르타 특별주의 주도로, 인구는 1,588,622명(2004년 기준)이며 면적은 32.5 km2, 인구밀도는 11,941명/km2이다.','https://ko.wikipedia.org/wiki/%EC%9A%95%EC%95%BC%EC%B9%B4%EB%A5%B4%ED%83%80'),
  ('yokohama','요코하마시는 일본 가나가와현 동부에 있는 시이자 가나가와현의 현청 소재지이다. 일본에서는 도쿄도 구부 다음 2번째로 인구가 많은 도시이다.','https://ko.wikipedia.org/wiki/%EC%9A%94%EC%BD%94%ED%95%98%EB%A7%88%EC%8B%9C'),
  ('zhangjiajie','장자제(중국어 간체자: 张家界, 정체자: 張家界, 병음: Zhāngjiājiè, 한자음: 장가계)는 중국의 후난성의 지급시이다. 면적은 9,516km2, 인구는 147만 6,521명 (2010년)이다.','https://ko.wikipedia.org/wiki/%EC%9E%A5%EC%9E%90%EC%A0%9C%EC%8B%9C'),
  ('zurich','취리히는 스위스에서 가장 큰 도시이자 취리히주의 주도이며, 스위스의 중간 지역에 취리히호의 북쪽 끝에 위치해 있다. 2020년 1월 기준으로 지방 자치 단체의 인구는 434,335명, 도시 지역(집적)은 131만 5000명(2009), 취리히 대도시 지역은 183만 명(2011년)이다.','https://ko.wikipedia.org/wiki/%EC%B7%A8%EB%A6%AC%ED%9E%88'),
  ('bilbao','빌바오는 스페인 바스크 지방의 중심 도시이다. 빌바오 시만의 인구는 2006년 기준으로 약 35만 명이고, 주변 지역을 포함하는 빌바오 대도시권의 인구는 바스크 지방 전체 인구의 약 1/3을 차지하는 95만여 명이다.','https://ko.wikipedia.org/wiki/%EB%B9%8C%EB%B0%94%EC%98%A4'),
  ('bled','블레트는 슬로베니아 북서부에 위치한 도시로 면적은 188.5km2, 인구는 10,899명(2002년 기준), 인구 밀도는 57.','https://ko.wikipedia.org/wiki/%EB%B8%94%EB%A0%88%ED%8A%B8'),
  ('bogota','보고타는 콜롬비아의 수도이며, 쿤디나마르카 주의 주도이기도 하다. 안데스산맥의 고원 분지(고도 2,600m)에 위치해 있다.','https://ko.wikipedia.org/wiki/%EB%B3%B4%EA%B3%A0%ED%83%80'),
  ('bologna','볼로냐는 이탈리아 북부 내륙에 있는 대학 도시이다. 세계에서 가장 오래된 대학으로 알려진 볼로냐 대학교가 있는 곳이다.','https://ko.wikipedia.org/wiki/%EB%B3%BC%EB%A1%9C%EB%83%90'),
  ('antalya','안탈리아는 지중해 연안에 위치한 튀르키예의 도시로 산으로 둘러싸인 이 도시는 안탈리아 주의 주도이며 특히 프로 축구 클럽들이 전지훈련을 위해 자주 찾는 도시로 잘 알려져 있다.','https://ko.wikipedia.org/wiki/%EC%95%88%ED%83%88%EB%A6%AC%EC%95%84'),
  ('banff','밴프(Banff)는 캐나다 앨버타주의 도시이다.','https://ko.wikipedia.org/wiki/%EB%B0%B4%ED%94%84'),
  ('bath','바스(Bath) 또는 배스는 영국 잉글랜드의 남서부 서머싯주에 위치한 도시로, 런던에서 서쪽으로 156 킬로미터와 브리스틀에서 남동쪽으로 21 킬로미터 떨어진 곳에 있다. 2011년을 기준으로 총 인구는 88,859명이다.','https://ko.wikipedia.org/wiki/%EB%B0%94%EC%8A%A4'),
  ('belgrade','베오그라드는 세르비아의 수도이자, 발칸반도의 주요 도시 중 하나이다. 베오그라드는 ‘하얀 도시’라는 뜻이다.','https://ko.wikipedia.org/wiki/%EB%B2%A0%EC%98%A4%EA%B7%B8%EB%9D%BC%EB%93%9C'),
  ('bergen','베르겐은 노르웨이 서남부, 베스틀란주에 있는 도시이다. 인구 25만(2008).','https://ko.wikipedia.org/wiki/%EB%B2%A0%EB%A5%B4%EA%B2%90'),
  ('casablanca','카사블랑카는 대서양에 위치한 모로코의 최대 도시이다. 도시 이름은 "하얀 집"을 뜻한다.','https://ko.wikipedia.org/wiki/%EC%B9%B4%EC%82%AC%EB%B8%94%EB%9E%91%EC%B9%B4'),
  ('cesky','체스키크룸로프는 체코 남보헤미아 주의 작은 도시이다. 《크룸로프 성》을 포함한 뛰어난 건축물과 역사 문화재로 유명하며, 체스키크룸로프 구 시가지는 유네스코 세계유산이다.','https://ko.wikipedia.org/wiki/%EC%B2%B4%EC%8A%A4%ED%82%A4%ED%81%AC%EB%A3%B8%EB%A1%9C%ED%94%84'),
  ('christchurch','크라이스트처치는 뉴질랜드의 남섬 동쪽에 있는 캔터버리 지방의 주요 도시로, 남섬에서 인구가 가장 많은 도시이다. 그리고 뉴질랜드 제3의 도시이다.','https://ko.wikipedia.org/wiki/%ED%81%AC%EB%9D%BC%EC%9D%B4%EC%8A%A4%ED%8A%B8%EC%B2%98%EC%B9%98'),
  ('cologne','쾰른은 독일 노르트라인베스트팔렌주의 도시이다. 베를린, 함부르크, 뮌헨에 이어 독일에서 가장 큰 도시로, 옛 프로이센에서는 베를린 다음으로 제2의 도시였다.','https://ko.wikipedia.org/wiki/%EC%BE%B0%EB%A5%B8'),
  ('como','코모는 이탈리아 롬바르디아주 코모도의 자치 단체의 하나로, 코모현의 행정 구역이다. 대 플리니우스와 소 플리니우스의 출신지로 알려져 있고, 고대 로마 시대에는 노붐오르가눔 코뭄(Novum Comum)으로 불렸다.','https://ko.wikipedia.org/wiki/%EC%BD%94%EB%AA%A8'),
  ('crete','크레타는 그리스에서 가장 큰 섬이자, 지중해에서 다섯 번째로 큰 섬이다. 고대 그리스부터 오늘날까지 역사, 신화, 음악, 방언 등 다방면에 있어 고유한 문화적 전통이 이 섬에 전해 내려왔다.','https://ko.wikipedia.org/wiki/%ED%81%AC%EB%A0%88%ED%83%80'),
  ('denver','덴버(Denver)는 콜로라도주에서 가장 큰 도시이자 주도이다. 2014년을 기준으로 덴버는 콜로라도 주에서 가장 인구가 많은 도시이다.','https://ko.wikipedia.org/wiki/%EB%8D%B4%EB%B2%84'),
  ('dresden','드레스덴은 독일 동부에 위치한 작센주의 주도로 엘베 강변에 위치해 있다. 작센 삼각 대도시권의 한 부분으로서, 예로부터 독일 남부 문화·정치·상공업의 중심지이다.','https://ko.wikipedia.org/wiki/%EB%93%9C%EB%A0%88%EC%8A%A4%EB%8D%B4'),
  ('fes','페스는 모로코 북부 지역 내륙에 있는 도시이며 페스메크네스 지방의 중심 도시이다. 2014년 인구 조사에 의하면 인구 111만으로, 모로코 내에서 두 번째로 큰 도시이다.','https://ko.wikipedia.org/wiki/%ED%8E%98%EC%8A%A4'),
  ('furano','후라노시는 일본 홋카이도 가미카와 지방 남부에 있는 시이다.','https://ko.wikipedia.org/wiki/%ED%9B%84%EB%9D%BC%EB%85%B8%EC%8B%9C'),
  ('galway','골웨이는 아일랜드 골웨이주의 주도이며, 아일랜드 제3의 도시이다. 면적은 54.','https://ko.wikipedia.org/wiki/%EA%B3%A8%EC%9B%A8%EC%9D%B4'),
  ('glasgow','글래스고는 스코틀랜드 최대의 항구 도시로 면적은 175.5km2, 인구는 612,040명(2016년 기준), 인구 밀도는 3,298명/km2이다.','https://ko.wikipedia.org/wiki/%EA%B8%80%EB%9E%98%EC%8A%A4%EA%B3%A0'),
  ('gothenburg','예테보리는 스웨덴에 있는 도시로 베스트라예탈란드주의 주도이다. 인구는 581,822명(2018년 기준)으로 수도 스톡홀름에 이어 스웨덴에서 두 번째로 큰 도시이다.','https://ko.wikipedia.org/wiki/%EC%98%88%ED%85%8C%EB%B3%B4%EB%A6%AC'),
  ('granada','그라나다는 스페인 안달루시아 지방에 위치한 그라나다도의 도청 소재지이다. 이베리아반도에 있었던 이슬람 세력의 마지막 근거지였으나, 1492년 이사벨 여왕에 의해 결국 함락되었으며, 이로써 레콩키스타가 완료되었다.','https://ko.wikipedia.org/wiki/%EA%B7%B8%EB%9D%BC%EB%82%98%EB%8B%A4'),
  ('grindelwald','그린델발트는 스위스 베른주에 위치한 도시로 면적은 171.08km2, 높이는 1,034m, 인구는 3,740명(2015년 기준), 인구 밀도는 22명/km2이다.','https://ko.wikipedia.org/wiki/%EA%B7%B8%EB%A6%B0%EB%8D%B8%EB%B0%9C%ED%8A%B8'),
  ('hallstatt','할슈타트는 오스트리아 오버외스터라이히주 그문덴군의 마을이다. 할슈타트호에 가까이 있으며 알프스 기슭의 호수 지역 잘츠카머구트 지방의 가장 안쪽에 위치하는 경승지이다.','https://ko.wikipedia.org/wiki/%ED%95%A0%EC%8A%88%ED%83%80%ED%8A%B8'),
  ('havana','아바나 또는 하바나는 쿠바의 수도이다. 서쪽에 치우쳐 있다.','https://ko.wikipedia.org/wiki/%EC%95%84%EB%B0%94%EB%82%98'),
  ('heidelberg','하이델베르크는 독일 라인강의 지류, 네카르강변의 대학도시·관광도시이다. 인구는 약 161,485명(2019년ㅇ기준)이다.','https://ko.wikipedia.org/wiki/%ED%95%98%EC%9D%B4%EB%8D%B8%EB%B2%A0%EB%A5%B4%ED%81%AC'),
  ('liverpool','리버풀(Liverpool)은 잉글랜드 북서부 머지사이드주의 도시로 2015년 기준으로 인구는 478,580 명이다. 머지강 어귀의 동쪽에 자리잡고 있다.','https://ko.wikipedia.org/wiki/%EB%A6%AC%EB%B2%84%ED%92%80'),
  ('ljubljana','류블랴나는 슬로베니아의 수도이다. 11개 특별시 중 하나로 지정되어 있다.','https://ko.wikipedia.org/wiki/%EB%A5%98%EB%B8%94%EB%9E%B4%EB%82%98'),
  ('lombok','롬복섬은 인도네시아 누사틍가라바랏 주의 섬이다. 소순다 열도의 일부로, 동쪽으로 롬복 해협을 끼고 발리섬이, 서쪽으로 알라스 해협을 끼고 숨바와섬이 위치한다.','https://ko.wikipedia.org/wiki/%EB%A1%AC%EB%B3%B5%EC%84%AC'),
  ('lucerne','루체른은 스위스 중부 루체른주에 있는 도시로, 루체른 주의 주도이다.','https://ko.wikipedia.org/wiki/%EB%A3%A8%EC%B2%B4%EB%A5%B8'),
  ('luxor','룩소르는 이집트의 남부에 있는 도시이다. 고대 이집트 시대부터 존재해 왔으며 인구는 376,022명(1999년)이고, 도시의 면적은 416km2이다.','https://ko.wikipedia.org/wiki/%EB%A3%A9%EC%86%8C%EB%A5%B4'),
  ('madeira','Madeira, officially the Autonomous Region of Madeira, is an autonomous region of Portugal, in the Atlantic Ocean about 805 km southwest of mainland Portugal. Together with the Azores, it is one of the two autonomous reg…','https://en.wikipedia.org/wiki/Madeira'),
  ('malacca','믈라카 또는 말라카는 말레이시아 믈라카주의 주도로, 말레이 반도 서해안 남부에 위치해, 동서 해양 교통의 요충 믈라카 해협에 면하는 항구도시이다. 말라카강(江) 어귀에 있으며 강의 좌안에 세인트폴 언덕이 솟아 있다.','https://ko.wikipedia.org/wiki/%EB%AF%88%EB%9D%BC%EC%B9%B4'),
  ('mallorca','마요르카섬은 지중해 발레아레스 제도에 있는 스페인에서 가장 큰 섬이다. 면적은 3,640.','https://ko.wikipedia.org/wiki/%EB%A7%88%EC%9A%94%EB%A5%B4%EC%B9%B4%EC%84%AC'),
  ('marseille','마르세유는 프랑스에서 두 번째로 큰 도시이다. 프로방스알프코트다쥐르 레지옹과 부슈뒤론주의 중심지이기도 하다.','https://ko.wikipedia.org/wiki/%EB%A7%88%EB%A5%B4%EC%84%B8%EC%9C%A0'),
  ('medellin','메데인 또는 메데진, 메델린은 콜롬비아에 있는 도시이다. 인구 2,499,080명으로 콜롬비아 제2위의 도시이며 콜롬비아 서부, 안티오키아주의 주도이다.','https://ko.wikipedia.org/wiki/%EB%A9%94%EB%8D%B0%EC%9D%B8'),
  ('montevideo','몬테비데오는 우루과이의 수도이자 최대의 무역항이며, 우루과이 국내에서 인구가 백만이 넘는 도시이다. 몬테비데오주의 주도이기도 하다.','https://ko.wikipedia.org/wiki/%EB%AA%AC%ED%85%8C%EB%B9%84%EB%8D%B0%EC%98%A4'),
  ('muscat','무스카트는 오만의 수도이자 최대 도시이다. 행정구역 상 무스카트주의 주도이며 2022년 기준 도시권을 포함하여 172만 명의 인구가 산다.','https://ko.wikipedia.org/wiki/%EB%AC%B4%EC%8A%A4%EC%B9%B4%ED%8A%B8'),
  ('mykonos','미코노스섬은 에게해 남쪽에 위치한 그리스의 섬으로 면적은 105.2km2, 높이는 364m, 인구는 9,320명(2001년 기준)이다.','https://ko.wikipedia.org/wiki/%EB%AF%B8%EC%BD%94%EB%85%B8%EC%8A%A4%EC%84%AC'),
  ('nadi','난디는 피지의 도시이며, 비치레부섬의 서부구에 위치해 있다. 인구는 42,284명(2007년 기준)이고, 피지에서 3번째로 인구가 많다.','https://ko.wikipedia.org/wiki/%EB%82%9C%EB%94%94'),
  ('nagasaki2','벳푸시는 일본 오이타현 중앙부에 있는 시이며 오이타현에서는 두 번째로 인구가 많다.','https://ko.wikipedia.org/wiki/%EB%B2%B3%ED%91%B8%EC%8B%9C'),
  ('nhatrang','냐짱 혹은 나트랑은 베트남 중남부에 위치한 카인호아성의 성도로, 호찌민시에서 북동쪽으로 약 450km 정도 떨어진 곳에 위치하며 면적은 251km2, 인구는 1,200,000명(2018)이다. 베트남에서 5번째로 큰 대도시이다.','https://ko.wikipedia.org/wiki/%EB%83%90%EC%A7%B1'),
  ('ottawa','오타와는 캐나다의 수도이자, 지방자치단체로 온타리오주 내에 두 번째로 큰 도시이다. 남 온타리오 동부의 오타와 밸리에 위치한 이 도시는 오타와강 남쪽 유역에 있으며, 주요 수로는 온타리오와 퀘벡 지방 사이의 지역 경계선을 형성한다.','https://ko.wikipedia.org/wiki/%EC%98%A4%ED%83%80%EC%99%80'),
  ('quebec','Quebec City is the capital city of the Canadian province of Quebec. As of July 2021, the city had a population of 549,459 and the Quebec City census metropolitan area had a population of 839,311.','https://en.wikipedia.org/wiki/Quebec_City'),
  ('quito','키토는 에콰도르의 수도이다. 과야킬 다음으로 인구가 많다.','https://ko.wikipedia.org/wiki/%ED%82%A4%ED%86%A0'),
  ('riga','리가는 라트비아의 수도로, 발트해와 다우가바강에 접해 있다. 리가는 발트 3국 가운데 가장 큰 도시(2011년 7월 현재 인구는 702,891명)이다.','https://ko.wikipedia.org/wiki/%EB%A6%AC%EA%B0%80'),
  ('rotorua','로토루아는 뉴질랜드 북섬에 있는 도시이다. 도시의 면적은 2,614.','https://ko.wikipedia.org/wiki/%EB%A1%9C%ED%86%A0%EB%A3%A8%EC%95%84'),
  ('rotterdam','로테르담은 네덜란드 자위트홀란트주에 있는 유럽 최대의 무역항 로테르담 항이 있는 도시이다. 인구는 약 60만명 이다.','https://ko.wikipedia.org/wiki/%EB%A1%9C%ED%85%8C%EB%A5%B4%EB%8B%B4'),
  ('samarkand','사마르칸트는 중앙아시아 두번째로 큰 우즈베키스탄의 고도이며, 사마르칸트 주의 주도이다. 소그드어로 ‘돌 요새’ 또는 ‘바위 도시’라는 의미이며, 몽골어(Самарканд)로는 ‘밤 바위’ 또는 ‘딱딱한 바위’를 의미한다.','https://ko.wikipedia.org/wiki/%EC%82%AC%EB%A7%88%EB%A5%B4%EC%B9%B8%ED%8A%B8'),
  ('sandiego','샌디에고는 미국 캘리포니아주 남부의 도시이다. 이름은 스페인어로 성 디다쿠스(Didacus of Alcalá)라는 뜻이다.','https://ko.wikipedia.org/wiki/%EC%83%8C%EB%94%94%EC%97%90%EA%B3%A0'),
  ('sansebastian','도노스티아는 산세바스티안 또는 스페인 바스크 지방 기푸스코아 주의 주도이다. 공식 명칭은 도노스티아-산세바스티안으로 도노스티아는 산세바스티안의 바스크어 이름이다.','https://ko.wikipedia.org/wiki/%EC%82%B0%EC%84%B8%EB%B0%94%EC%8A%A4%ED%8B%B0%EC%95%88'),
  ('santorini','산토리니섬, 공식적으로 티라는 그리스 에게해 남부에 있는 작고 둥근 모양의 화산 군도이며, 그리스 본토와 약 200킬로미터 떨어져 있다. 키클라데스 제도의 최남단에 자리잡고 있으며, 면적은 73제곱킬로미터이다.','https://ko.wikipedia.org/wiki/%EC%82%B0%ED%86%A0%EB%A6%AC%EB%8B%88%EC%84%AC'),
  ('shanghai','상하이는 중화인민공화국의 4개 직할시 중 하나이다. 상하이는 장강 동쪽 하류에 위치하고 있으며, 황푸강이 도시를 관통하여 흐른다.','https://ko.wikipedia.org/wiki/%EC%83%81%ED%95%98%EC%9D%B4%EC%8B%9C'),
  ('shirakawago','시라카와고(白川郷 )는 일본 기후현 쇼 강 유역의 호칭이다.','https://ko.wikipedia.org/wiki/%EC%8B%9C%EB%9D%BC%EC%B9%B4%EC%99%80%EA%B3%A0'),
  ('siemreap','시엠립은 캄보디아 시엠립주의 주도이다. 씨엠립은 17세기 타이의 아유타야 왕조와의 전쟁에서 승리한 것과 관련이 있다.','https://ko.wikipedia.org/wiki/%EC%8B%9C%EC%97%A0%EB%A6%BD'),
  ('siena','시에나는 이탈리아 중부 토스카나주의 도시로, 시에나도의 도청 소재지이다.','https://ko.wikipedia.org/wiki/%EC%8B%9C%EC%97%90%EB%82%98'),
  ('sintra','신트라는 포르투갈 리스보아 지방 리스본현에 위치한 도시이다. 무어인이 쌓은 성곽, 포르투갈 왕실의 여름 궁전 등 다양한 연대의 문화재가 많기 때문에 관광지로 널리 알려진 곳이다.','https://ko.wikipedia.org/wiki/%EC%8B%A0%ED%8A%B8%EB%9D%BC'),
  ('sofia','소피아는 불가리아의 수도이자 최대 도시이다. 유럽에서 가장 오래된 수도의 하나이다.','https://ko.wikipedia.org/wiki/%EC%86%8C%ED%94%BC%EC%95%84'),
  ('sokcho','속초시(束草市)는 대한민국 강원특별자치도 동해안 북부에 위치한 시이다. 시의 서쪽으로 설악산 국립공원이 있고, 시의 중심부에는 석호인 영랑호와 청초호가 있다.','https://ko.wikipedia.org/wiki/%EC%86%8D%EC%B4%88%EC%8B%9C'),
  ('split','스플리트는 크로아티아 서남부 스플리트달마티아주에 있는 도시이다. 인구 221,456(2007).','https://ko.wikipedia.org/wiki/%EC%8A%A4%ED%94%8C%EB%A6%AC%ED%8A%B8'),
  ('verona','베로나(Verona)는 거주 인구 255,131명을 지닌 이탈리아 베네토 지방에서 두 번째로 큰 도시이다. 베네토 지역의 일곱 개 도청 소재지 중 한 곳이며, 베네토 지방 및 이탈리아 북동부 지방자치단체 도시 중 가장 넓다.','https://ko.wikipedia.org/wiki/%EB%B2%A0%EB%A1%9C%EB%82%98'),
  ('vilnius','빌뉴스는 리투아니아의 수도이다. 전간기에는 리투아니아 대공국, 후에 폴란드-리투아니아 연방의 영토였다.','https://ko.wikipedia.org/wiki/%EB%B9%8C%EB%89%B4%EC%8A%A4'),
  ('wellington','웰링턴은 뉴질랜드의 수도이다. 1865년 오클랜드로부터 이곳으로 수도를 옮겼으며, 오클랜드에 이어 뉴질랜드에서 두 번째로 큰 도시이다.','https://ko.wikipedia.org/wiki/%EC%9B%B0%EB%A7%81%ED%84%B4'),
  ('york','요크(York)는 영국 잉글랜드 노스요크셔주에 있는 도시이다. 우즈강과 포스강의 합류점에 위치한다.','https://ko.wikipedia.org/wiki/%EC%9A%94%ED%81%AC'),
  ('zagreb','자그레브는 크로아티아의 수도이다. 자그레브는 크로아티아의 북서쪽, 다뉴브 강의 지류인 사바강 변에 위치해 있고, 메드베드니차 산의 남쪽에 위치해있다.','https://ko.wikipedia.org/wiki/%EC%9E%90%EA%B7%B8%EB%A0%88%EB%B8%8C'),
  ('zanzibar','잔지바르는 동아프리카 탄자니아에 위치한 자치령으로, 웅구자섬(잔지바르섬)과 펨바섬을 중심으로 한 잔지바르 제도로 이루어져 있다. 잔지바르에 있는 스톤 타운은 세계유산으로 지정되었으며, 육두구, 계피, 후추 등의 향신료 산지로 유명하다.','https://ko.wikipedia.org/wiki/%EC%9E%94%EC%A7%80%EB%B0%94%EB%A5%B4'),
  ('zermatt','체르마트는 스위스 발레주에 위치한 도시로 면적은 242.69km2, 높이는 1,608m, 인구는 5,720명(2010년 기준), 인구 밀도는 24명/km2이다.','https://ko.wikipedia.org/wiki/%EC%B2%B4%EB%A5%B4%EB%A7%88%ED%8A%B8')

) as v(id, txt, url)
where c.id = v.id;

select count(*) filter (where summary is not null) as 설명있음,
       count(*) filter (where summary is null)     as 설명없음,
       count(*)                                    as 전체
  from public.cities;
