-- =====================================================================
-- UN 195개국을 countries 에 다 넣습니다 (113개국 추가)
--
-- ⚠⚠ **075 보다 먼저 돌리십시오.** cities 를 넣는 SQL 은 currency 를
--   countries 에서 join 으로 가져오는데, **그 나라가 없으면 그 줄이
--   조용히 빠집니다.** 049 에서 비슈케크 하나가 그렇게 사라졌고, 지금은
--   88개국뿐이라 107개국이 통째로 빠집니다.
--
-- 이름:   CLDR 한국어(Intl.DisplayNames). 몇은 우리말에서 더 흔한 쪽으로
--         손봤습니다 — 호주 · 남아프리카공화국 · 콩고 공화국 ·
--         콩고 민주 공화국 · 중앙아프리카공화국 · 도미니카 연방.
-- 통화·공용어: GeoNames countryInfo.txt
-- 대륙:   un.js 의 UN_BY_CONT (아시아 48 · 유럽 44 · 아프리카 54 ·
--         북아메리카 23 · 남아메리카 12 · 오세아니아 14 = 195).
--   ⚠ 홈 화면의 대륙 캐러셀이 이 분모를 씁니다. 여기서 한 나라라도 다른
--     대륙에 넣으면 **같은 앱이 두 가지 수를 말합니다.**
-- 기본 시간대: 그 나라에서 인구가 제일 많은 도시의 시간대(GeoNames).
--
-- 여러 번 실행해도 안전합니다.
-- 만든 것: tools/citypick.pl — 손으로 고치지 말고 그쪽을 고치십시오.
-- =====================================================================

insert into public.countries (code, name, name_en, currency, local_lang, continent, default_timezone)
values
  ('AD', '안도라', 'Andorra', 'EUR', 'ca', '유럽', 'Europe/Andorra'),
  ('AF', '아프가니스탄', 'Afghanistan', 'AFN', 'fa', '아시아', 'Asia/Kabul'),
  ('AG', '앤티가 바부다', 'Antigua and Barbuda', 'XCD', 'en', '북아메리카', 'America/Antigua'),
  ('AL', '알바니아', 'Albania', 'ALL', 'sq', '유럽', 'Europe/Tirane'),
  ('AM', '아르메니아', 'Armenia', 'AMD', 'hy', '아시아', 'Asia/Yerevan'),
  ('AO', '앙골라', 'Angola', 'AOA', 'pt', '아프리카', 'Africa/Luanda'),
  ('BA', '보스니아 헤르체고비나', 'Bosnia and Herzegovina', 'BAM', 'bs', '유럽', 'Europe/Sarajevo'),
  ('BB', '바베이도스', 'Barbados', 'BBD', 'en', '북아메리카', 'America/Barbados'),
  ('BD', '방글라데시', 'Bangladesh', 'BDT', 'bn', '아시아', 'Asia/Dhaka'),
  ('BF', '부르키나파소', 'Burkina Faso', 'XOF', 'fr', '아프리카', 'Africa/Ouagadougou'),
  ('BH', '바레인', 'Bahrain', 'BHD', 'ar', '아시아', 'Asia/Bahrain'),
  ('BI', '부룬디', 'Burundi', 'BIF', 'fr', '아프리카', 'Africa/Bujumbura'),
  ('BJ', '베냉', 'Benin', 'XOF', 'fr', '아프리카', 'Africa/Porto-Novo'),
  ('BS', '바하마', 'Bahamas', 'BSD', 'en', '북아메리카', 'America/Nassau'),
  ('BT', '부탄', 'Bhutan', 'BTN', 'dz', '아시아', 'Asia/Thimphu'),
  ('BW', '보츠와나', 'Botswana', 'BWP', 'en', '아프리카', 'Africa/Gaborone'),
  ('BY', '벨라루스', 'Belarus', 'BYN', 'be', '유럽', 'Europe/Minsk'),
  ('BZ', '벨리즈', 'Belize', 'BZD', 'en', '북아메리카', 'America/Belize'),
  ('CD', '콩고 민주 공화국', 'Democratic Republic of the Congo', 'CDF', 'fr', '아프리카', 'Africa/Kinshasa'),
  ('CF', '중앙아프리카공화국', 'Central African Republic', 'XAF', 'fr', '아프리카', 'Africa/Bangui'),
  ('CG', '콩고 공화국', 'Republic of the Congo', 'XAF', 'fr', '아프리카', 'Africa/Brazzaville'),
  ('CI', '코트디부아르', 'Ivory Coast', 'XOF', 'fr', '아프리카', 'Africa/Abidjan'),
  ('CM', '카메룬', 'Cameroon', 'XAF', 'en', '아프리카', 'Africa/Douala'),
  ('CV', '카보베르데', 'Cabo Verde', 'CVE', 'pt', '아프리카', 'Atlantic/Cape_Verde'),
  ('CY', '키프로스', 'Cyprus', 'EUR', 'el', '아시아', 'Asia/Nicosia'),
  ('DJ', '지부티', 'Djibouti', 'DJF', 'fr', '아프리카', 'Africa/Djibouti'),
  ('DM', '도미니카 연방', 'Dominica', 'XCD', 'en', '북아메리카', 'America/Dominica'),
  ('DO', '도미니카 공화국', 'Dominican Republic', 'DOP', 'es', '북아메리카', 'America/Santo_Domingo'),
  ('DZ', '알제리', 'Algeria', 'DZD', 'ar', '아프리카', 'Africa/Algiers'),
  ('ER', '에리트리아', 'Eritrea', 'ERN', 'aa', '아프리카', 'Africa/Asmara'),
  ('ET', '에티오피아', 'Ethiopia', 'ETB', 'am', '아프리카', 'Africa/Addis_Ababa'),
  ('FM', '미크로네시아', 'Micronesia', 'USD', 'en', '오세아니아', 'Pacific/Chuuk'),
  ('GA', '가봉', 'Gabon', 'XAF', 'fr', '아프리카', 'Africa/Libreville'),
  ('GD', '그레나다', 'Grenada', 'XCD', 'en', '북아메리카', 'America/Grenada'),
  ('GH', '가나', 'Ghana', 'GHS', 'en', '아프리카', 'Africa/Accra'),
  ('GM', '감비아', 'Gambia', 'GMD', 'en', '아프리카', 'Africa/Banjul'),
  ('GN', '기니', 'Guinea', 'GNF', 'fr', '아프리카', 'Africa/Conakry'),
  ('GQ', '적도 기니', 'Equatorial Guinea', 'XAF', 'es', '아프리카', 'Africa/Malabo'),
  ('GT', '과테말라', 'Guatemala', 'GTQ', 'es', '북아메리카', 'America/Guatemala'),
  ('GW', '기니비사우', 'Guinea-Bissau', 'XOF', 'pt', '아프리카', 'Africa/Bissau'),
  ('GY', '가이아나', 'Guyana', 'GYD', 'en', '남아메리카', 'America/Guyana'),
  ('HN', '온두라스', 'Honduras', 'HNL', 'es', '북아메리카', 'America/Tegucigalpa'),
  ('HT', '아이티', 'Haiti', 'HTG', 'ht', '북아메리카', 'America/Port-au-Prince'),
  ('IQ', '이라크', 'Iraq', 'IQD', 'ar', '아시아', 'Asia/Baghdad'),
  ('IR', '이란', 'Iran', 'IRR', 'fa', '아시아', 'Asia/Tehran'),
  ('JM', '자메이카', 'Jamaica', 'JMD', 'en', '북아메리카', 'America/Jamaica'),
  ('KI', '키리바시', 'Kiribati', 'AUD', 'en', '오세아니아', 'Pacific/Tarawa'),
  ('KM', '코모로', 'Comoros', 'KMF', 'ar', '아프리카', 'Indian/Comoro'),
  ('KN', '세인트키츠 네비스', 'Saint Kitts and Nevis', 'XCD', 'en', '북아메리카', 'America/St_Kitts'),
  ('KP', '북한', 'North Korea', 'KPW', 'ko', '아시아', 'Asia/Pyongyang'),
  ('KW', '쿠웨이트', 'Kuwait', 'KWD', 'ar', '아시아', 'Asia/Kuwait'),
  ('LB', '레바논', 'Lebanon', 'LBP', 'ar', '아시아', 'Asia/Beirut'),
  ('LC', '세인트루시아', 'Saint Lucia', 'XCD', 'en', '북아메리카', 'America/St_Lucia'),
  ('LI', '리히텐슈타인', 'Liechtenstein', 'CHF', 'de', '유럽', 'Europe/Vaduz'),
  ('LR', '라이베리아', 'Liberia', 'LRD', 'en', '아프리카', 'Africa/Monrovia'),
  ('LS', '레소토', 'Lesotho', 'LSL', 'en', '아프리카', 'Africa/Maseru'),
  ('LU', '룩셈부르크', 'Luxembourg', 'EUR', 'lb', '유럽', 'Europe/Luxembourg'),
  ('LY', '리비아', 'Libya', 'LYD', 'ar', '아프리카', 'Africa/Tripoli'),
  ('MC', '모나코', 'Monaco', 'EUR', 'fr', '유럽', 'Europe/Monaco'),
  ('MD', '몰도바', 'Moldova', 'MDL', 'ro', '유럽', 'Europe/Chisinau'),
  ('ME', '몬테네그로', 'Montenegro', 'EUR', 'sr', '유럽', 'Europe/Podgorica'),
  ('MG', '마다가스카르', 'Madagascar', 'MGA', 'fr', '아프리카', 'Indian/Antananarivo'),
  ('MH', '마셜 제도', 'Marshall Islands', 'USD', 'mh', '오세아니아', 'Pacific/Majuro'),
  ('MK', '북마케도니아', 'North Macedonia', 'MKD', 'mk', '유럽', 'Europe/Skopje'),
  ('ML', '말리', 'Mali', 'XOF', 'fr', '아프리카', 'Africa/Bamako'),
  ('MR', '모리타니', 'Mauritania', 'MRU', 'ar', '아프리카', 'Africa/Nouakchott'),
  ('MU', '모리셔스', 'Mauritius', 'MUR', 'en', '아프리카', 'Indian/Mauritius'),
  ('MW', '말라위', 'Malawi', 'MWK', 'ny', '아프리카', 'Africa/Blantyre'),
  ('MZ', '모잠비크', 'Mozambique', 'MZN', 'pt', '아프리카', 'Africa/Maputo'),
  ('NA', '나미비아', 'Namibia', 'NAD', 'en', '아프리카', 'Africa/Windhoek'),
  ('NE', '니제르', 'Niger', 'XOF', 'fr', '아프리카', 'Africa/Niamey'),
  ('NG', '나이지리아', 'Nigeria', 'NGN', 'en', '아프리카', 'Africa/Lagos'),
  ('NI', '니카라과', 'Nicaragua', 'NIO', 'es', '북아메리카', 'America/Managua'),
  ('NR', '나우루', 'Nauru', 'AUD', 'na', '오세아니아', 'Pacific/Nauru'),
  ('PA', '파나마', 'Panama', 'PAB', 'es', '북아메리카', 'America/Panama'),
  ('PG', '파푸아뉴기니', 'Papua New Guinea', 'PGK', 'en', '오세아니아', 'Pacific/Port_Moresby'),
  ('PK', '파키스탄', 'Pakistan', 'PKR', 'ur', '아시아', 'Asia/Karachi'),
  ('PS', '팔레스타인', 'Palestinian Territory', 'ILS', 'ar', '아시아', 'Asia/Hebron'),
  ('PW', '팔라우', 'Palau', 'USD', 'pau', '오세아니아', 'Pacific/Palau'),
  ('PY', '파라과이', 'Paraguay', 'PYG', 'es', '남아메리카', 'America/Asuncion'),
  ('RU', '러시아', 'Russia', 'RUB', 'ru', '유럽', 'Europe/Moscow'),
  ('RW', '르완다', 'Rwanda', 'RWF', 'rw', '아프리카', 'Africa/Kigali'),
  ('SB', '솔로몬 제도', 'Solomon Islands', 'SBD', 'en', '오세아니아', 'Pacific/Guadalcanal'),
  ('SC', '세이셸', 'Seychelles', 'SCR', 'en', '아프리카', 'Indian/Mahe'),
  ('SD', '수단', 'Sudan', 'SDG', 'ar', '아프리카', 'Africa/Khartoum'),
  ('SL', '시에라리온', 'Sierra Leone', 'SLE', 'en', '아프리카', 'Africa/Freetown'),
  ('SM', '산마리노', 'San Marino', 'EUR', 'it', '유럽', 'Europe/San_Marino'),
  ('SN', '세네갈', 'Senegal', 'XOF', 'fr', '아프리카', 'Africa/Dakar'),
  ('SO', '소말리아', 'Somalia', 'SOS', 'so', '아프리카', 'Africa/Mogadishu'),
  ('SR', '수리남', 'Suriname', 'SRD', 'nl', '남아메리카', 'America/Paramaribo'),
  ('SS', '남수단', 'South Sudan', 'SSP', 'en', '아프리카', 'Africa/Juba'),
  ('ST', '상투메 프린시페', 'Sao Tome and Principe', 'STN', 'pt', '아프리카', 'Africa/Sao_Tome'),
  ('SV', '엘살바도르', 'El Salvador', 'USD', 'es', '북아메리카', 'America/El_Salvador'),
  ('SY', '시리아', 'Syria', 'SYP', 'ar', '아시아', 'Asia/Damascus'),
  ('SZ', '에스와티니', 'Eswatini', 'SZL', 'en', '아프리카', 'Africa/Mbabane'),
  ('TD', '차드', 'Chad', 'XAF', 'fr', '아프리카', 'Africa/Ndjamena'),
  ('TG', '토고', 'Togo', 'XOF', 'fr', '아프리카', 'Africa/Lome'),
  ('TJ', '타지키스탄', 'Tajikistan', 'TJS', 'tg', '아시아', 'Asia/Dushanbe'),
  ('TL', '동티모르', 'Timor Leste', 'USD', 'tet', '아시아', 'Asia/Dili'),
  ('TM', '투르크메니스탄', 'Turkmenistan', 'TMT', 'tk', '아시아', 'Asia/Ashgabat'),
  ('TO', '통가', 'Tonga', 'TOP', 'to', '오세아니아', 'Pacific/Tongatapu'),
  ('TT', '트리니다드 토바고', 'Trinidad and Tobago', 'TTD', 'en', '북아메리카', 'America/Port_of_Spain'),
  ('TV', '투발루', 'Tuvalu', 'AUD', 'tvl', '오세아니아', 'Pacific/Funafuti'),
  ('UA', '우크라이나', 'Ukraine', 'UAH', 'uk', '유럽', 'Europe/Kyiv'),
  ('UG', '우간다', 'Uganda', 'UGX', 'en', '아프리카', 'Africa/Kampala'),
  ('VA', '바티칸 시국', 'Vatican', 'EUR', 'la', '유럽', 'Europe/Vatican'),
  ('VC', '세인트빈센트 그레나딘', 'Saint Vincent and the Grenadines', 'XCD', 'en', '북아메리카', 'America/St_Vincent'),
  ('VE', '베네수엘라', 'Venezuela', 'VES', 'es', '남아메리카', 'America/Caracas'),
  ('VU', '바누아투', 'Vanuatu', 'VUV', 'bi', '오세아니아', 'Pacific/Efate'),
  ('WS', '사모아', 'Samoa', 'WST', 'sm', '오세아니아', 'Pacific/Apia'),
  ('YE', '예멘', 'Yemen', 'YER', 'ar', '아시아', 'Asia/Aden'),
  ('ZM', '잠비아', 'Zambia', 'ZMW', 'en', '아프리카', 'Africa/Lusaka'),
  ('ZW', '짐바브웨', 'Zimbabwe', 'ZWG', 'en', '아프리카', 'Africa/Harare')
on conflict (code) do nothing;

-- ── 이미 있던 줄의 빈 칸만 메웁니다 (덮어쓰지 않습니다) ──────────────
update public.countries c set
  continent        = coalesce(nullif(c.continent, ''),        nullif(v.continent, '')),
  default_timezone = coalesce(nullif(c.default_timezone, ''), nullif(v.tz, '')),
  currency         = coalesce(nullif(c.currency, ''),         nullif(v.currency, ''))
from (values
  ('AD', '유럽', 'Europe/Andorra', 'EUR'),
  ('AE', '아시아', 'Asia/Dubai', 'AED'),
  ('AF', '아시아', 'Asia/Kabul', 'AFN'),
  ('AG', '북아메리카', 'America/Antigua', 'XCD'),
  ('AL', '유럽', 'Europe/Tirane', 'ALL'),
  ('AM', '아시아', 'Asia/Yerevan', 'AMD'),
  ('AO', '아프리카', 'Africa/Luanda', 'AOA'),
  ('AR', '남아메리카', 'America/Argentina/Buenos_Aires', 'ARS'),
  ('AT', '유럽', 'Europe/Vienna', 'EUR'),
  ('AU', '오세아니아', 'Australia/Sydney', 'AUD'),
  ('AZ', '아시아', 'Asia/Baku', 'AZN'),
  ('BA', '유럽', 'Europe/Sarajevo', 'BAM'),
  ('BB', '북아메리카', 'America/Barbados', 'BBD'),
  ('BD', '아시아', 'Asia/Dhaka', 'BDT'),
  ('BE', '유럽', 'Europe/Brussels', 'EUR'),
  ('BF', '아프리카', 'Africa/Ouagadougou', 'XOF'),
  ('BG', '유럽', 'Europe/Sofia', 'BGN'),
  ('BH', '아시아', 'Asia/Bahrain', 'BHD'),
  ('BI', '아프리카', 'Africa/Bujumbura', 'BIF'),
  ('BJ', '아프리카', 'Africa/Porto-Novo', 'XOF'),
  ('BN', '아시아', 'Asia/Brunei', 'BND'),
  ('BO', '남아메리카', 'America/La_Paz', 'BOB'),
  ('BR', '남아메리카', 'America/Sao_Paulo', 'BRL'),
  ('BS', '북아메리카', 'America/Nassau', 'BSD'),
  ('BT', '아시아', 'Asia/Thimphu', 'BTN'),
  ('BW', '아프리카', 'Africa/Gaborone', 'BWP'),
  ('BY', '유럽', 'Europe/Minsk', 'BYN'),
  ('BZ', '북아메리카', 'America/Belize', 'BZD'),
  ('CA', '북아메리카', 'America/Toronto', 'CAD'),
  ('CD', '아프리카', 'Africa/Kinshasa', 'CDF'),
  ('CF', '아프리카', 'Africa/Bangui', 'XAF'),
  ('CG', '아프리카', 'Africa/Brazzaville', 'XAF'),
  ('CH', '유럽', 'Europe/Zurich', 'CHF'),
  ('CI', '아프리카', 'Africa/Abidjan', 'XOF'),
  ('CL', '남아메리카', 'America/Santiago', 'CLP'),
  ('CM', '아프리카', 'Africa/Douala', 'XAF'),
  ('CN', '아시아', 'Asia/Shanghai', 'CNY'),
  ('CO', '남아메리카', 'America/Bogota', 'COP'),
  ('CR', '북아메리카', 'America/Costa_Rica', 'CRC'),
  ('CU', '북아메리카', 'America/Havana', 'CUP'),
  ('CV', '아프리카', 'Atlantic/Cape_Verde', 'CVE'),
  ('CY', '아시아', 'Asia/Nicosia', 'EUR'),
  ('CZ', '유럽', 'Europe/Prague', 'CZK'),
  ('DE', '유럽', 'Europe/Berlin', 'EUR'),
  ('DJ', '아프리카', 'Africa/Djibouti', 'DJF'),
  ('DK', '유럽', 'Europe/Copenhagen', 'DKK'),
  ('DM', '북아메리카', 'America/Dominica', 'XCD'),
  ('DO', '북아메리카', 'America/Santo_Domingo', 'DOP'),
  ('DZ', '아프리카', 'Africa/Algiers', 'DZD'),
  ('EC', '남아메리카', 'America/Guayaquil', 'USD'),
  ('EE', '유럽', 'Europe/Tallinn', 'EUR'),
  ('EG', '아프리카', 'Africa/Cairo', 'EGP'),
  ('ER', '아프리카', 'Africa/Asmara', 'ERN'),
  ('ES', '유럽', 'Europe/Madrid', 'EUR'),
  ('ET', '아프리카', 'Africa/Addis_Ababa', 'ETB'),
  ('FI', '유럽', 'Europe/Helsinki', 'EUR'),
  ('FJ', '오세아니아', 'Pacific/Fiji', 'FJD'),
  ('FM', '오세아니아', 'Pacific/Chuuk', 'USD'),
  ('FR', '유럽', 'Europe/Paris', 'EUR'),
  ('GA', '아프리카', 'Africa/Libreville', 'XAF'),
  ('GB', '유럽', 'Europe/London', 'GBP'),
  ('GD', '북아메리카', 'America/Grenada', 'XCD'),
  ('GE', '아시아', 'Asia/Tbilisi', 'GEL'),
  ('GH', '아프리카', 'Africa/Accra', 'GHS'),
  ('GM', '아프리카', 'Africa/Banjul', 'GMD'),
  ('GN', '아프리카', 'Africa/Conakry', 'GNF'),
  ('GQ', '아프리카', 'Africa/Malabo', 'XAF'),
  ('GR', '유럽', 'Europe/Athens', 'EUR'),
  ('GT', '북아메리카', 'America/Guatemala', 'GTQ'),
  ('GW', '아프리카', 'Africa/Bissau', 'XOF'),
  ('GY', '남아메리카', 'America/Guyana', 'GYD'),
  ('HN', '북아메리카', 'America/Tegucigalpa', 'HNL'),
  ('HR', '유럽', 'Europe/Zagreb', 'EUR'),
  ('HT', '북아메리카', 'America/Port-au-Prince', 'HTG'),
  ('HU', '유럽', 'Europe/Budapest', 'HUF'),
  ('ID', '아시아', 'Asia/Jakarta', 'IDR'),
  ('IE', '유럽', 'Europe/Dublin', 'EUR'),
  ('IL', '아시아', 'Asia/Jerusalem', 'ILS'),
  ('IN', '아시아', 'Asia/Kolkata', 'INR'),
  ('IQ', '아시아', 'Asia/Baghdad', 'IQD'),
  ('IR', '아시아', 'Asia/Tehran', 'IRR'),
  ('IS', '유럽', 'Atlantic/Reykjavik', 'ISK'),
  ('IT', '유럽', 'Europe/Rome', 'EUR'),
  ('JM', '북아메리카', 'America/Jamaica', 'JMD'),
  ('JO', '아시아', 'Asia/Amman', 'JOD'),
  ('JP', '아시아', 'Asia/Tokyo', 'JPY'),
  ('KE', '아프리카', 'Africa/Nairobi', 'KES'),
  ('KG', '아시아', 'Asia/Bishkek', 'KGS'),
  ('KH', '아시아', 'Asia/Phnom_Penh', 'KHR'),
  ('KI', '오세아니아', 'Pacific/Tarawa', 'AUD'),
  ('KM', '아프리카', 'Indian/Comoro', 'KMF'),
  ('KN', '북아메리카', 'America/St_Kitts', 'XCD'),
  ('KP', '아시아', 'Asia/Pyongyang', 'KPW'),
  ('KR', '아시아', 'Asia/Seoul', 'KRW'),
  ('KW', '아시아', 'Asia/Kuwait', 'KWD'),
  ('KZ', '아시아', 'Asia/Almaty', 'KZT'),
  ('LA', '아시아', 'Asia/Vientiane', 'LAK'),
  ('LB', '아시아', 'Asia/Beirut', 'LBP'),
  ('LC', '북아메리카', 'America/St_Lucia', 'XCD'),
  ('LI', '유럽', 'Europe/Vaduz', 'CHF'),
  ('LK', '아시아', 'Asia/Colombo', 'LKR'),
  ('LR', '아프리카', 'Africa/Monrovia', 'LRD'),
  ('LS', '아프리카', 'Africa/Maseru', 'LSL'),
  ('LT', '유럽', 'Europe/Vilnius', 'EUR'),
  ('LU', '유럽', 'Europe/Luxembourg', 'EUR'),
  ('LV', '유럽', 'Europe/Riga', 'EUR'),
  ('LY', '아프리카', 'Africa/Tripoli', 'LYD'),
  ('MA', '아프리카', 'Africa/Casablanca', 'MAD'),
  ('MC', '유럽', 'Europe/Monaco', 'EUR'),
  ('MD', '유럽', 'Europe/Chisinau', 'MDL'),
  ('ME', '유럽', 'Europe/Podgorica', 'EUR'),
  ('MG', '아프리카', 'Indian/Antananarivo', 'MGA'),
  ('MH', '오세아니아', 'Pacific/Majuro', 'USD'),
  ('MK', '유럽', 'Europe/Skopje', 'MKD'),
  ('ML', '아프리카', 'Africa/Bamako', 'XOF'),
  ('MM', '아시아', 'Asia/Yangon', 'MMK'),
  ('MN', '아시아', 'Asia/Ulaanbaatar', 'MNT'),
  ('MR', '아프리카', 'Africa/Nouakchott', 'MRU'),
  ('MT', '유럽', 'Europe/Malta', 'EUR'),
  ('MU', '아프리카', 'Indian/Mauritius', 'MUR'),
  ('MV', '아시아', 'Indian/Maldives', 'MVR'),
  ('MW', '아프리카', 'Africa/Blantyre', 'MWK'),
  ('MX', '북아메리카', 'America/Mexico_City', 'MXN'),
  ('MY', '아시아', 'Asia/Kuala_Lumpur', 'MYR'),
  ('MZ', '아프리카', 'Africa/Maputo', 'MZN'),
  ('NA', '아프리카', 'Africa/Windhoek', 'NAD'),
  ('NE', '아프리카', 'Africa/Niamey', 'XOF'),
  ('NG', '아프리카', 'Africa/Lagos', 'NGN'),
  ('NI', '북아메리카', 'America/Managua', 'NIO'),
  ('NL', '유럽', 'Europe/Amsterdam', 'EUR'),
  ('NO', '유럽', 'Europe/Oslo', 'NOK'),
  ('NP', '아시아', 'Asia/Kathmandu', 'NPR'),
  ('NR', '오세아니아', 'Pacific/Nauru', 'AUD'),
  ('NZ', '오세아니아', 'Pacific/Auckland', 'NZD'),
  ('OM', '아시아', 'Asia/Muscat', 'OMR'),
  ('PA', '북아메리카', 'America/Panama', 'PAB'),
  ('PE', '남아메리카', 'America/Lima', 'PEN'),
  ('PG', '오세아니아', 'Pacific/Port_Moresby', 'PGK'),
  ('PH', '아시아', 'Asia/Manila', 'PHP'),
  ('PK', '아시아', 'Asia/Karachi', 'PKR'),
  ('PL', '유럽', 'Europe/Warsaw', 'PLN'),
  ('PS', '아시아', 'Asia/Hebron', 'ILS'),
  ('PT', '유럽', 'Europe/Lisbon', 'EUR'),
  ('PW', '오세아니아', 'Pacific/Palau', 'USD'),
  ('PY', '남아메리카', 'America/Asuncion', 'PYG'),
  ('QA', '아시아', 'Asia/Qatar', 'QAR'),
  ('RO', '유럽', 'Europe/Bucharest', 'RON'),
  ('RS', '유럽', 'Europe/Belgrade', 'RSD'),
  ('RU', '유럽', 'Europe/Moscow', 'RUB'),
  ('RW', '아프리카', 'Africa/Kigali', 'RWF'),
  ('SA', '아시아', 'Asia/Riyadh', 'SAR'),
  ('SB', '오세아니아', 'Pacific/Guadalcanal', 'SBD'),
  ('SC', '아프리카', 'Indian/Mahe', 'SCR'),
  ('SD', '아프리카', 'Africa/Khartoum', 'SDG'),
  ('SE', '유럽', 'Europe/Stockholm', 'SEK'),
  ('SG', '아시아', 'Asia/Singapore', 'SGD'),
  ('SI', '유럽', 'Europe/Ljubljana', 'EUR'),
  ('SK', '유럽', 'Europe/Bratislava', 'EUR'),
  ('SL', '아프리카', 'Africa/Freetown', 'SLE'),
  ('SM', '유럽', 'Europe/San_Marino', 'EUR'),
  ('SN', '아프리카', 'Africa/Dakar', 'XOF'),
  ('SO', '아프리카', 'Africa/Mogadishu', 'SOS'),
  ('SR', '남아메리카', 'America/Paramaribo', 'SRD'),
  ('SS', '아프리카', 'Africa/Juba', 'SSP'),
  ('ST', '아프리카', 'Africa/Sao_Tome', 'STN'),
  ('SV', '북아메리카', 'America/El_Salvador', 'USD'),
  ('SY', '아시아', 'Asia/Damascus', 'SYP'),
  ('SZ', '아프리카', 'Africa/Mbabane', 'SZL'),
  ('TD', '아프리카', 'Africa/Ndjamena', 'XAF'),
  ('TG', '아프리카', 'Africa/Lome', 'XOF'),
  ('TH', '아시아', 'Asia/Bangkok', 'THB'),
  ('TJ', '아시아', 'Asia/Dushanbe', 'TJS'),
  ('TL', '아시아', 'Asia/Dili', 'USD'),
  ('TM', '아시아', 'Asia/Ashgabat', 'TMT'),
  ('TN', '아프리카', 'Africa/Tunis', 'TND'),
  ('TO', '오세아니아', 'Pacific/Tongatapu', 'TOP'),
  ('TR', '아시아', 'Europe/Istanbul', 'TRY'),
  ('TT', '북아메리카', 'America/Port_of_Spain', 'TTD'),
  ('TV', '오세아니아', 'Pacific/Funafuti', 'AUD'),
  ('TZ', '아프리카', 'Africa/Dar_es_Salaam', 'TZS'),
  ('UA', '유럽', 'Europe/Kyiv', 'UAH'),
  ('UG', '아프리카', 'Africa/Kampala', 'UGX'),
  ('US', '북아메리카', 'America/New_York', 'USD'),
  ('UY', '남아메리카', 'America/Montevideo', 'UYU'),
  ('UZ', '아시아', 'Asia/Tashkent', 'UZS'),
  ('VA', '유럽', 'Europe/Vatican', 'EUR'),
  ('VC', '북아메리카', 'America/St_Vincent', 'XCD'),
  ('VE', '남아메리카', 'America/Caracas', 'VES'),
  ('VN', '아시아', 'Asia/Ho_Chi_Minh', 'VND'),
  ('VU', '오세아니아', 'Pacific/Efate', 'VUV'),
  ('WS', '오세아니아', 'Pacific/Apia', 'WST'),
  ('YE', '아시아', 'Asia/Aden', 'YER'),
  ('ZA', '아프리카', 'Africa/Johannesburg', 'ZAR'),
  ('ZM', '아프리카', 'Africa/Lusaka', 'ZMW'),
  ('ZW', '아프리카', 'Africa/Harare', 'ZWG')
) as v(code, continent, tz, currency)
where c.code = v.code
  and (c.continent is null or c.continent = ''
    or c.default_timezone is null or c.default_timezone = ''
    or c.currency is null or c.currency = '');

-- ── 확인 ─────────────────────────────────────────────────────────────
-- 1번이 195 이상이어야 합니다(괌·홍콩·마카오처럼 UN 회원국이 아닌 것도
-- 이미 들어 있어서 조금 더 큽니다).
select * from (
  select 1 as ord, 'countries 전체'::text as 확인, count(*)::text as 결과
    from public.countries
  union all
  select 2, '통화가 빈 나라',
         coalesce((select string_agg(code, ' ' order by code) from public.countries
                    where currency is null or currency = ''), '없음')
  union all
  select 3, '대륙이 빈 나라',
         coalesce((select string_agg(code, ' ' order by code) from public.countries
                    where continent is null or continent = ''), '없음')
) t order by ord;
